### ISSUE TITLE
all: decide whether examples that need making RPC calls should run and return an error

### ISSUE THREAD

**Issue by shantuo** [google/go-cloud#1109]
A lot of our examples show how to use the underlying API, which normally requires making an RPC calls. See #1083 , we let it run by providing the output line and it returns an error. The good thing is we know the path running works and we got some test coverage. While the example would become longer and have some error handling logic which may not be necessary for the purpose of an example.

**Comment by jba** [comment]
If by examples you mean the contents of `examples_test.go` files, we shouldn't expect them to run, just compile. (Unless they are testing non-network functionality.)

For examples to be readable, they shouldn't have too much logic. Errors should be "handled" with code like
```
if err != nil {
    // TODO: handle error
}
```
and we should simplify other things too. If we make them run during tests by providing the output line, we will have some very hard-to-debug tests.

I think every package should have _samples_, which are production-quality and runnable. We can add tests to those.

**Comment by vangent** [comment]
I've been updating most of our `example_test.go` examples to run, using fake/invalid credentials. They run, and get an expected and repeatable error; the code outputs something like "ReadAll failed due to invalid credentials" (it doesn't include the specific error).

I don't think this approach adds too much complexity to the example in terms of handling errors, but in some cases it does add extra code to create the fake credentials.

I was mostly doing this because:
1. I found at least one bug in example code, which wasn't caught because it wasn't running. I don't remember where this was.
2. Having them run added some test coverage, mainly for public constructors (since the tests tend to use private constructors).

I'm open to turning all of the examples back to compile-only, and simplifying them where possible, as long as we also add tests for the coverage that's lost by doing so.

I'm not sure how feasible samples are for every package, since for most of our packages making them runnable implies provisioning something on a Cloud provider. Unless you are referring to something more like the tutorial or guestbook samples, which do include Terraform files etc. for the provisioning; but it's still hard to use those in tests.
