### ISSUE TITLE
blob/s3blob: URL opening doesn't work with "MissingRegion" error

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#1357]
When I create a `blob.Bucket` with URL `s3://mybucket`, reads and writes fail with an error like `MissingRegion: could not find region configuration`.

**Comment by zombiezen** [comment]
As per the [AWS session docs](https://godoc.org/github.com/aws/aws-sdk-go/aws/session#hdr-Environment_Variables), it seems that this can be remedied while running by setting the `AWS_REGION` environment variable, which is what our samples do.

I wanted to understand this issue in a bit more depth, so I looked around at the [S3 Using Buckets docs](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html#access-bucket-intro) which led me to the [S3 Virtual Hosting of Buckets docs](https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html). In S3 Using Buckets, it states that:

> In a virtual-hosted–style URL, you can use either of [`http://bucket.s3.amazonaws.com` or `http://bucket.s3-aws-region.amazonaws.com`]. If you make a request to the `http://bucket.s3.amazonaws.com` endpoint, the DNS has sufficient information to route your request directly to the Region where your bucket resides.

So this would be fine and allow for us to safely ignore the region. Except! The [`ValidateEndpointHandler`](https://godoc.org/github.com/aws/aws-sdk-go/aws/corehandlers#ValidateEndpointHandler) that is [installed in every session](https://github.com/aws/aws-sdk-go/blob/112e8a372b3f46d410ed416decd09cc06a05e3b0/aws/session/session.go#L347) checks to see whether region is filled in for every request, which is what is causing the error above. Even if we bypassed that check, there's another snag: S3 buckets that contain dots will be served with an incorrect TLS certificate, as noted in [Virtual Hosting of Buckets](https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html):

> When using virtual hosted–style buckets with SSL, the SSL wild card certificate only matches buckets that do not contain periods. To work around this, use HTTP or write your own certificate verification logic.

So this gets us back to where we started in the general case: a correct region is required in order to interact with an S3 bucket. I'm beginning to think that this should be a required parameter of `s3blob.NewBucket`, not just an optional parameter. I would say that we could infer the region if not specified, but [`s3manager.GetBucketRegion`](https://godoc.org/github.com/aws/aws-sdk-go/service/s3/s3manager#GetBucketRegion) requires a region to be specified _in order to determine the bucket's region_.

**Comment by zombiezen** [comment]
I have verified that setting `AWS_REGION` will fix the issue. I'll send a PR to update.

Interestingly, the `~/.aws/config` file is not consulted [unless you set `AWS_SDK_LOAD_CONFIG` to true](https://godoc.org/github.com/aws/aws-sdk-go/aws/session#hdr-Sessions_from_Shared_Config). I'm leaning towards having the default session that the URL opener uses (as well as what's in the Wire provider sets) set [`SharedConfigEnable`](https://godoc.org/github.com/aws/aws-sdk-go/aws/session#SharedConfigEnable). I'm uncertain of the full implications of this, but it would make it easier to go from `aws init` to working Go CDK application without much thought.

**Comment by vangent** [comment]
Note: https://github.com/google/go-cloud/issues/1416 is tracking the `SharedConfigEnable` issue.
