### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by asim** [google/go-cloud#1411]
All implementation packages appear to have the higher level abstraction name as a suffix. This seems redundant and actually syntactically not very nice. Ideally it should be stripped so `pubsub/mempubsub` becomes `pubsub/memory`. Any thoughts?

**Comment by jba** [comment]
The problem is that only the last component of the path is used in the importing file, so it can be hard to understand what package a symbol comes from when looking at the code. That's especially a problem for common names like `test`, which is why you see package paths like `net/http/httptest`. We decided to follow that principle throughout.

**Comment by asim** [comment]
Thanks for clarifying.

**Comment by asim** [comment]
Sorry not to bother you but here's an example refactor at the high level https://github.com/asim/go-cloud. Personally I think its a much cleaner approach but I can understand where you're coming from.

**Comment by eliben** [comment]
Asim, in your refactor if I want to import the Azure blob and Azure pubsub, I end up with:
```

import "gocloud.dev/blob/azure"
import "gocloud.dev/pubsub/azure"

```
So you'll need to rename the imports in all importing file to something, otherwise "azure" collides with itself and also says nothing about what kind of API it is.

**Comment by asim** [comment]
I guess its a tradeoff in terms of where you want to provide convenience or readability. I don't think its too much of an issue for the user to have named imports in the case where these do collide.
