### ISSUE TITLE
all: make URL parameters more natural for URLOpeners

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#1488]
Escaping URLs in URL parameters is icky, and there are several providers where URLs are needed (e.g., `etcdvar` for the etcd server, `blobvar` for the `OpenBucket` URL), and it would be nice to be able to use the main URL itself more naturally (e.g., `etcd+http://my.etcd.server:8080?var=myvar` instead of the current `etcd://myvar?client=http://my.etcd.server:8080`).

This requires some work in the URL registration to make it so that URLs that start with `etcd+` (for example) are sent to `etcdvar`, not just ones that have the exact scheme `etcd`.

**Comment by jba** [comment]
> URLs that start with `etcd+`

nit: That's not a URL, or even a URI. I don't think `url.Parse` will work on it.

**Comment by vangent** [comment]
The scheme is ` a sequence of characters beginning with a letter and followed by any combination of letters, digits, plus (+), period (.), or hyphen (-)`, so I think it's valid.

`url.Parse` does work on it.

**Comment by jba** [comment]
Oh, I see. Cool. Never saw a `+` in a scheme before.

**Comment by vangent** [comment]
Update: Most of those "URL as URL query parameter" requirements have gone away now that I've updated drivers to be more consistent with the suggestions [here](https://github.com/google/go-cloud/blob/master/internal/docs/design.md#urls) about having default openers get things from the environment.

The remaining one is in `runtimevar/blobvar`, which takes a `bucket` query parameter (it also keeps a cache of opened buckets, and does refcounting to close them). IMHO it would be more consistent with other providers to have the default bucket come from an environment variable, the `URLOpener` have the `*blob.Bucket` (not a `*blob.URLMux`), and drop the caching/refcounting. @zombiezen thoughts?

**Comment by zombiezen** [comment]
I have thoughts, but sadly nothing conclusive over the last few days.

One consideration is whether all blobvars will be contained in the same bucket for an application. If we were to use an environment variable, then users cannot use the `runtimevar.OpenVariable` function to obtain a `blobvar` in the multi-bucket scenario, which seems an unfortunate consequence. Using an environment variable makes sense for `etcd` because it's fairly common for all variables to come from the same `etcd` instance. However, I don't have a similar intuition for buckets, which causes me pause.

The other aspect that I've been thinking about this is that it still remains surprising that such a `blobvar` URL would not contain all the information that identifies that resource that the `blobvar` would be using.

@vangent pointed out to me that there are some tricky corner cases to consider: if a query parameter is used by both the bucket opener and the `blobvar` opener, there would not be a trivial way to pass it to the underlying bucket opener. I don't know how to resolve that, or how likely it would be.

**Comment by vangent** [comment]
>  I don't have a similar intuition for buckets

My intuition is that configuration for an application is unlikely to reside in multiple buckets. I'd go further and say that most applications will only have 1-2 configurations they are watching.

> it still remains surprising that such a blobvar URL would not contain
> all the information that identifies that resource that the blobvar
> would be using

Yes, this is true, but I don't think it's any different than the `etcdvar` or `vault` or `rabbit` URLs not having everything about the resource they are attaching to.



I feel like we should err on the side of "simple" here, and make `blobvar` default to a single bucket. It makes `blobvar` much much simpler to use (no URLs in URLs) and to implement (no caching, no refcounting). We can always add complexity later if we get demand for it.

**Comment by zombiezen** [comment]
I suppose, but it would be a URL format change later, likely requiring a different scheme.

**Comment by vangent** [comment]
I think we could just add the "bucket" URL parameter back, it would be backwards compatible. Again, this is the same deal as many other providers.

I'm going to send a PR for this change.
