### ISSUE TITLE
sql/BigQuery: Is it possible to support it ?

### ISSUE THREAD

**Issue by gedw99** [google/go-cloud#1627]
### Is your feature request related to a problem? Please describe.

Need bigquery for massive datasets.
On premise and in the cloud postresql is fine.
But we currently stream out data to bigquery and so it would be good for the same golang SQL code to work with both postresql and bigquery. 

I looked into Standard SQL support for BigQuery which is there. I think its 2011 standard ?

**Comment by zombiezen** [comment]
I think the idea of having a `database/sql` driver for BigQuery is a good one, but I don't think the Go CDK is the right place for it. Go CDK only creates types for services that are reasonably similar across a few different cloud providers, and the only other similar platform to BigQuery that I'm aware of is Snowflake. As such, I don't think this is in scope for the Go CDK.

This would make for a good feature request for `cloud.google.com/go/bigquery`. You can file an issue over at [their repo's issue tracker](https://github.com/googleapis/google-cloud-go/issues/new)

**Comment by vangent** [comment]
It appears there are available ODBC driver(s) for BigQuery that should allow you to create a `sql.DB` pointing to BigQuery, which you can then use to make SQL queries. `sql.DB` is a semi-portable type that comes with Go itself; the Go CDK provides some wrappers for instantiating `sql.DB` for various providers, but in this case you can certainly do that yourself. (`sql.DB` is only semi-portable because there's no guarantee that the SQL queries will work the same against different backends; e.g., Postgres SQL queries may not work as-is against BigQuery).

ODBC driver:
https://cloud.google.com/bigquery/providers/simba-drivers/

BigQuery SQL syntax:
https://cloud.google.com/bigquery/docs/reference/standard-sql/

We may separately consider a portable API for big data processing (e.g., BigQuery/Snowflake/Redshift).

Hope that helps.
