### ISSUE TITLE
pubsub/azuresb: update SendAcks to use Bulk instead of a separate AMQP connection

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#1764]
@vsaroopchand said:

I actually fixed this in the SB SDK; this custom SendAck can use the newly added Bulk Operation. I'll rework SendAck once this is merged in.

https://github.com/Azure/azure-service-bus-go/pull/99

**Comment by vsaroopchand** [comment]
The newly added SendBatchDisposition operation in the SB SDK throws a 410 error on double acks. How should I handle this?

    --- FAIL: TestConformance/TestDoubleAck (29.48s)
        drivertest.go:518: unhandled error link 3213f1e1-c837-4678-8037-91be22e03c14: status code 410 and description: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue.

**Comment by vangent** [comment]
The current code has the same issue:
https://github.com/google/go-cloud/blob/master/pubsub/azuresb/azuresb.go#L505

It's unfortunate that the batch API returns a single error; it's not clear what the semantics are (e.g., how many of the acks succeeded vs failed? what if some of them failed with one error code and others for another error code? which specific message(s) caused the error(s)?).

The current solution is to swallow the error if the error is a 401 and only for a single message. If the RPC is for more than one message, and the whole RPC returns a 401, retry the messages one at a time ignoring 401 errors.

This isn't ideal, but I'm not sure it's possible to do better without a more expressive response from Bulk. For example, [AWS](https://github.com/google/go-cloud/blob/master/pubsub/awssnssqs/awssnssqs.go#L502) returns success from its batch API, but the response has a list of failures in it. GCP doesn't return an error for double-acks/nacks.

**Comment by eliben** [comment]
Should the title be saying `blob/azblob` or is this a pubsub issue?

**Comment by vangent** [comment]
It's `pubsub`; updated.

**Comment by vsaroopchand** [comment]
Added an Issue and PR to resolve this in SB SDK
https://github.com/Azure/azure-service-bus-go/issues/128

**Comment by jakebjorkekato** [comment]
We were having issues w/ the internal amqp link not getting its claim refreshed after Microsoft updated their library and the update was pulled into here (links to PRs below)

https://github.com/Azure/azure-service-bus-go/pull/137
https://github.com/google/go-cloud/pull/2605

Updating these was useful because the AMQP links claims expire after 2 hours (this seems to be controlled by the service).

We have been working with a forked version in a staging environment to validate these authentication issues.

While the Microsoft library fix seemed to work, the internal AMQP link maintained by the `pubsub/azuresb` `subscription` object does not have anything refreshing its claims.

What we began to see was that after 2 hours ack/nack messages were failing, but not reads.

I created a very quick proof of concept which I am testing now that may be a direction to head towards resolving this issue.

https://github.com/jakebjorkekato/go-cloud/pull/2/files

Please note that rather than retrying or anything, it just combines all of the errors and spits them out purely so the information is preserved.
