### ISSUE TITLE
blob: add an option to support cross-bucket copies

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#1766]
* Could be a "SourceBucket *blob.Bucket" option in `CopyOptions`.
* The source bucket would need to be of the same provider type as the active one, or the portable type would return an error (to copy across providers, you need to read/write).

**Comment by jba** [comment]
nit/cognitive quirk: When I write `myBucket.Copy(..., foo, bar)`, it feels like I'm copying _from_ myBucket to somewhere else. So I feel that `DestBucket` would be more natural. But maybe that's just me.

This actually brings up a problem with your existing `Copy` method: you list the args as `src, dest`, which feels natural. But Go does it the other way: the `copy` built-in uses `dest, src`. It's not a minor point, since getting it wrong could result in data loss. Consider renaming it `CopyTo`, or reversing the arg order and naming it `CopyFrom`.

There is another thing to consider. GCS has the ability to _compose_ one object out of one or more other objects. The composed object is a sequence of pointers to the other objects, but behaves like their concatenation for reading. I don't know if this is something we want to support, but it might affect the design. You can see what we did in `cloud.google.com/go/storage`: We used the "from" direction, which meant that copying and composing 
 calls looked the same, except that compose took variadic args. (https://godoc.org/cloud.google.com/go/storage#ObjectHandle.ComposerFrom). I don't think you could do that here because of the need for options at the end, but I just wanted to mention it.

**Comment by vangent** [comment]
> But Go does it the other way

Fixed in the PR.

**Comment by eliben** [comment]
Which implementations is this issue still blocked on?

**Comment by vangent** [comment]
All, plus the portable type (i.e., this feature has not been started at all).

**Comment by howie** [comment]
Would it be possible to have cross-bucket (cross-cloud on fly copy)?
Such as [azure-storage-azcopy](https://github.com/Azure/azure-storage-azcopy), but it only provide copy file from s3 to azure blob.

**Comment by vangent** [comment]
You can do cross-cloud and cross-bucket copies by instantiating a `Bucket` for each, creating a `blob.Reader` using `NewReader` for the source blob and a `blob.Writer` using `NewWriter` for the destination, and calling `io.Copy` (https://golang.org/pkg/io/#Copy).

There's not really a better way to do cross-cloud copies.

This bug is about adding a way to do cross-bucket copies within a cloud provider, which some providers provide an optimized API for. The optimization is that the copy can happen on the cloud side without downloading and then re-uploading all of the blob's bytes.
