### ISSUE TITLE
all: Why As and not a type assertion?

### ISSUE THREAD

**Issue by nhooyr** [google/go-cloud#1790]
Why do the concrete types have a `As` method that takes an interface and returns true if the interface was 

Why not have a method like `Underlying` that return an `interface{}` that can then be type asserted to the cloud specific provider type?

Seems simpler.

**Comment by vangent** [comment]
We considered that, specifically something like [os.ProcessState.Sys](https://golang.org/pkg/os/#ProcessState.Sys) that returns an `interface{}` that the user can cast/type assert.

We ended up going with `As` (which is consistent with the Go 2 proposal for errors, currently implemented in [xerrors](https://godoc.org/golang.org/x/xerrors#As)) because:
* Most portable types have an `As` function for errors, and using `As` will make it easy to implement those for chained errors once they arrive.
* As adds more flexibility for drivers to support conversions to multiple types (i.e., not that there are multiple possibly underlying types, but that a single underlying type can be converted to multiple types). Chained errors is one example of this, where the top-level error may always be the same type, but may represent a chain of other errors. Another example is that a driver might choose to support `As`-level compatibility with another driver; e.g., driver `foo` could support all of the `As` types defined by `s3blob`, converting them internally, and then any code that runs with driver `s3blob` would also work with driver `foo` (even if it uses the `As` escape hatches).

I thought we had documented this design decision somewhere, but I can't find it, so I'll send a PR to add it to design.md.
