### ISSUE TITLE
gcppubsub: conformance tests -record fails in clean client

### ISSUE THREAD

**Issue by eliben** [google/go-cloud#1972]
### Describe the bug

Running conformance tests recording fails in `pubsub/gcppubsub`

### To Reproduce

In a clean master client (with proper credentials):

```
cd pubsub/gcppubsub
go test -v --record
```

Getting failure:

```
    --- FAIL: TestConformance/TestNack (0.36s)
        replay.go:187: Recording into golden file testdata/TestConformance/TestNack.replay
        drivertest.go:342: creating topic: rpc error: code = AlreadyExists desc = Resource already exists in the project (resource=TestConformance_TestNack-topic-1).
 ```

**Comment by jba** [comment]
As a general rule, I don't think our tests should create resources. That should be done once per project/account and out of band, by terraform or a shell script.

**Comment by eliben** [comment]
> As a general rule, I don't think our tests should create resources. That should be done once per project/account and out of band, by terraform or a shell script.

Agreed

**Comment by vangent** [comment]
You should be able to unblock this by going to the UI and deleting that
topic (and likely subscription as well). It's likely that the tests were
interrupted and didn't get a chance to clean up after themselves.

A one time provisioning using terraform might work, but would likely lead
to other forms of flakiness (e.g. undelivered messages remaining in a topic
between runs).

**Comment by eliben** [comment]
Thanks, @vangent this fixed the problem for this test.

I think it's ok for tests to create topics/subscriptions as long as they clean up after themselves. It could help if we modified the test to remove these topics/subscriptions if they already exist before creating. WDYT?

**Comment by vangent** [comment]
Sure, that would make them more stable, but it might also make them slower. Probably fine since `-record` doesn't happen often. They might still be flaky since some providers don't let you delete and then recreate a resource quickly (you get an error that says try again in 1 minute or whatever).

Another approach would be to create a new *different* topic/subscription every time (e.g., put timestamp in the name), but then we'd likely strand them.

**Comment by eliben** [comment]
> Sure, that would make them more stable, but it might also make them slower. Probably fine since `-record` doesn't happen often. They might still be flaky since some providers don't let you delete and then recreate a resource quickly (you get an error that says try again in 1 minute or whatever).
> 

I was thinking keep the code as it is now, but also add a check to delete topics if they already exist before the test starts. This would be rare in practice (only when these leftovers happen)

> Another approach would be to create a new _different_ topic/subscription every time (e.g., put timestamp in the name), but then we'd likely strand them.

This could work too. Since the tests do cleanup most of the time the number of orphaned topics should be small

**Comment by jba** [comment]
In my experience, there are many orphans. But we ran integration tests in CI.

We went with different topics on each run because we were worried about concurrent runs—what if the CI or a teammate is running the test at the same time as you? That's not a concern for us because we use replay. So let's keep it simple. Even simpler than deleting is to ignore the Create error if it's `AlreadyExists`.

**Comment by eliben** [comment]
> Even simpler than deleting is to ignore the Create error if it's `AlreadyExists`.

But then what about leftover messages in the topic from the previous test run? These can fail the test.

Actually your point about concurrent runs is good too. Theoretically, multiple team members could be recording at the same time (or at least testing with recording on). I guess we were just getting lucky until now

**Comment by jba** [comment]
I don't think concurrent execution is worth worrying about. Recording is rare.

Leftover messages can be a problem, though. So delete + create may be best.

**Comment by eliben** [comment]
#1989 is a straw-man to address this for gcppubsub
