### ISSUE TITLE
internal/cmd/gocdk: `add-api` command should be `demo`

### ISSUE THREAD

**Issue by clausti** [google/go-cloud#2077]
Per feedback that having a dash in the middle of the command is undesirable, change the `add-api [PORTABLE_API_NAME]` command to be `demo [PORTABLE_API_NAME]`.

**Comment by eliben** [comment]
Should it be something like `gocdk demo add <api name>` instead? Just `demo` gives me the intuition that something is going to happen / start running, whereas we only generate code as a result. Since we'll have to have two levels with `gocdk <command> <verb> <params>` anyway for other commands, might as well do this for demos/adding apis. Could be `gocdk api add <api name>` too

**Comment by vangent** [comment]
Yes, we will expand to use subcommands soon. We'll probably have `gocdk demo add`, `gocdk demo list`, and maybe `gocdk demo remove`. We don't have support for subcommands yet so I was just using "demo" for now.
