### ISSUE TITLE
docstore: test mongo driver on Azure Cosmos

### ISSUE THREAD

**Issue by jba** [google/go-cloud#2088]
Make sure we can use our mongoDB driver against Azure Cosmos. If necessary, add code to simplify the experience.

**Comment by jba** [comment]
We should always be testing Cosmos via our conformance tests.

**Comment by vsaroopchand** [comment]
@shantuo Let me know if I can help with this issue. CosmosDB support a couple of different API types, MongoDb is one of them.  [Here](https://docs.microsoft.com/en-us/azure/cosmos-db/create-mongodb-golang) is the getting started sample.

**Comment by jba** [comment]
@vsaroopchand we'd love your help. If you'd like to look over and try our docstore API, we'd love the feedback.

**Comment by vsaroopchand** [comment]
Sure, I'll give it a try and provide feedback.

**Comment by shantuo** [comment]
Hi @vsaroopchand , just want to know whether you have a chance to try it?

**Comment by vsaroopchand** [comment]
Hi @shantuo , sorry for the delayed response on this. I ran the conformation tests for mongo (mongo_test.go) against a CosmosDB Mongo API and it succeeded. After running the tests, I did notice a **docstore-test** DB and two corresponding Collections added to Cosmos.

**TestConformance Results**
Running tool: C:\Go\bin\go.exe test -timeout 30s gocloud.dev/internal/docstore/mongodocstore -run ^(TestConformance)$

ok  	gocloud.dev/internal/docstore/mongodocstore	17.343s
Success: Tests passed.

**LowerCase Test Result:**
Running tool: C:\Go\bin\go.exe test -timeout 30s gocloud.dev/internal/docstore/mongodocstore -run ^(TestLowercaseFields)$

ok      gocloud.dev/internal/docstore/mongodocstore 1.110s
Success: Tests passed.



**Benchmark Test Results: Initially this failed due to rate limiting. Once I manually up the provisioned RUs, re-ran and tests passed **
 
goos: windows
goarch: amd64
pkg: gocloud.dev/internal/docstore/mongodocstore
BenchmarkConformance/BenchmarkSingleActionPut-4                   50      25859532 ns/op      138044 B/op       2382 allocs/op
BenchmarkConformance/BenchmarkSingleActionGet-4                  200      10681250 ns/op       62058 B/op       1181 allocs/op
BenchmarkConformance/BenchmarkActionListPut-4                     10     120951390 ns/op      485680 B/op       7374 allocs/op
BenchmarkConformance/BenchmarkActionListGet-4                    300       5093982 ns/op      376069 B/op       5200 allocs/op
PASS
ok      gocloud.dev/internal/docstore/mongodocstore 12.391s
Success: Benchmarks passed.

**Comment by jba** [comment]
Thanks, @vsaroopchand.
