### ISSUE TITLE
all: consider a portable API for task queue

### ISSUE THREAD

**Issue by jba** [google/go-cloud#2141]
A _task queue service_ allows a program to enqueue tasks for later execution by workers. It is similar to a pub/sub system, but it has different use cases, features and performance characteristics. Compare [Google Cloud Pub/Sub](https://cloud.google.com/pubsub) with [Google Cloud Tasks](https://cloud.google.com/tasks) for example.

Other providers may not distinguish these two services. For instance, I think Azure Service Bus is designed to be used for both pub/sub and tasks. So there may not be a portable API to write here.

**Comment by vsaroopchand** [comment]
Whats the difference between Task and a Message?  After reviewing Google Cloud Tasks, I can't say there is a similar Azure Service except for the Service Bus which has both Topics (Pub/Sub) and Queues (traditional FIFO).

**Comment by jba** [comment]
The differences in the Google services are (1) the "subscriber" is an actual application that is doing work; (2) you can schedule work in the future. Probably some other things too. But that may be just how Google decided to divide up the problem. I think other providers like Azure handle both cases with a single service.

**Comment by tonyhb** [comment]
@vangent @vsaroopchand could we consider re-opening?

Tasks are slightly different from events (there are multiple google products: https://cloud.google.com/tasks vs https://cloud.google.com/pubsub).

Differences:

- Tasks can be scheduled, events cannot
- Tasks are consumed by a single subscriber, events are consumed by multiple
- Therefore, retries of a task are consumed by a single subscriber and are easier to manage
- Tasks can have exponential backoff
- Tasks can be optionally deduplicated

These differences are subtle but important (and I suppose that's why we have two google cloud products for them).

NATS also handles them differently (but doesn't allow scheduling) using queue groups: https://docs.nats.io/nats-concepts/queue.
