### ISSUE TITLE
blob: bucket writer has no 'abandon' or 'discard' functionality

### ISSUE THREAD

**Issue by EdSchouten** [google/go-cloud#222]
When inserting a large blob into a bucket, there is often a desire to stream a value from some source (e.g., a large file on disk). This process may fail halfway, meaning there should be some way to discard a partially written file.

The [`Writer` object](https://godoc.org/github.com/google/go-cloud/blob#Writer) only has a `Write()` and `Close()` function, but no method to cancel the write itself. Should such a function be added? Noteworthy: The Minio and S3 libraries solve this by not having a `Writer`-like object, but instead have a function that takes a `Reader` and consumes the data.

**Comment by ijt** [comment]
I'm thinking the proposed method should attempt to revert the writer object and the bucket back to the state right after calling `bucket.NewWriter()`. With that in mind, it seems like a better name for the method would be `Reset()`.

**Comment by ijt** [comment]
@zombiezen suggested offline that we call the method `Abort()` and have it put the object into a terminal state such that it cannot be used anymore. He pointed out that this is easier to test and would allow associated resources to be freed up. I agree.

**Comment by ijt** [comment]
I tried a straightforward approach of just deleting the blob that has been written so far, but it raised a question that I don't see how to answer without adopting the approach in issue #353. Suppose a write has failed due to a network partition and we want to abort. If the network partition persists then it won't work to delete what has already been written to the cloud. So what's already up there will continue to be in its partially finished state. The question is: how should we deal with this?

If we add an atomicblob package supporting ACID semantics then we can get an `Abort` method that doesn't have this defect. The contents for the key to be written won't be updated until `Close` is called, so the only thing that could be left in an incomplete state would be the blob contents of a temporary key.

**Comment by ijt** [comment]
I'm backing off from this issue to focus on pub/sub. If someone else wants to take this on while I work on that, I'm happy to share my work-in-progress branch and context. Otherwise, I'll return to this later.

**Comment by zombiezen** [comment]
Summarizing from offline conversation with @ijt:

At least on GCS and S3, this ability to stop an in-progress upload already exists natively in the providers (although I am hazy on particular mechanisms. @shantuo, do you know how these work?). For `fileblob`, we can get the atomic semantics by using temporary files and moving them on successful `Close`. However, the blob driver needs to add a new method. At this early stage, it's fine for us to just add this as a required method of a blob driver (a breaking change).

**Comment by msample** [comment]
Partially finished multipart uploads due to network outages, exceeded retries, kill -9 on the client, etc will happen. It is unreasonable to expect the client to persistently retain upload metadata to clean it up later in all cases.

This approach works fine with S3 if you configure the S3 lifecycle management on the bucket to remove unfinished uploads after a number of days (to avoid getting billed for storage of data you can't access).  It also meets what I was seeking in #340 - objects don't trigger cloud/lambda functions unless they were completed properly.

**Comment by zombiezen** [comment]
@msample Do you have a link to docs for the relevant S3 lifecycle management? That would be helpful here.

**Comment by msample** [comment]
yes - https://docs.aws.amazon.com/AmazonS3/latest/dev/mpuoverview.html#mpu-abort-incomplete-mpu-lifecycle-config

This feature came quite recently. Before that, one had to run a periodic job to find these unfinished uploads and clean each of them of explicitly.

**Comment by vsaroopchand** [comment]
I just want to summarize how Azure Storage [SDK](github.com/Azure/azure-storage-blob-go/2018-03-28/azblob) handles this. In this scenario, assuming you use [put-block](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block) to stage a new blob, it is considered uncommitted until you explicitly [commit](https://docs.microsoft.com/rest/api/storageservices/put-block-list) or [delete](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block). The delete operation works on both committed and uncommitted blobs.

**Comment by vangent** [comment]
I agree with @msample that it is unreasonable to expect the client to clean up everything on the server side. Given that, I don't think we need an explicit Abort() method; cancelling the [Context provided to to the Writer](https://github.com/google/go-cloud/blob/master/blob/blob.go#L180) should be sufficient.

This is what GCS and S3 both do as well (GCS Writer has a `CloseWithError` but it's marked deprecated in favor of closing the Context; S3 Uploader doesn't have any explicit Abort).

@EdSchouten does that sound reasonable?

For this issue, I'd like to update the docstring to make this more clear, and to add a conformance test that starting a write, then cancelling the context before calling Close, results in the file not being readable.

**Comment by EdSchouten** [comment]
SGTM! \o/
