### ISSUE TITLE
docstore: support a start position for queries

### ISSUE THREAD

**Issue by jba** [google/go-cloud#2251]
It should be possible to start a query at a particular document.

**Comment by jba** [comment]
Each provider has a different way of describing where a query starts:

- Firestore: The `StartAt` field of [StructuredQuery](https://cloud.google.com/firestore/docs/reference/rpc/google.firestore.v1#google.firestore.v1.StructuredQuery). 
- MongoDB: `Skip` in [`FindOptions`](https://godoc.org/go.mongodb.org/mongo-driver/mongo/options#FindOptions)
- DynamoDB: `ExclusiveStartKey` in [`QueryInput`](https://godoc.org/github.com/aws/aws-sdk-go/service/dynamodb#QueryInput) or `ScanInput`.

**Comment by jba** [comment]
Let's think about this another way. I believe that the main use case (possibly the only use case) for a start position is to resume a query where it was left off. For example, a server renders a page of query results, along with a "Next" button. The user clicks the button, and the server must then resume the query to generate the next page.

We can support this use case with an easy-to-use and portable API. Calling `DocumentIterator.Snapshot` returns a string. When you pass that string to `ResumeQuery`, you  get back a `DocumentIterator` in the same state. It looks like this:
```
iter := coll.Query().Where("x", ">", 3).Get(ctx)
... iter.Next(...) ...
snap := iter.Snapshot()
...
iter := coll.ResumeQuery(snap)
... use iter as before ...
```

The implementation of `DocumentIterator.Snapshot` would serialize the query and the current position of the iterator, then base64-encode it to get an easy-to-use string. Each driver could encode the current position in a way that made it easy to resume. For example, the mongo driver would record the number of documents already returned, so that to resume it could call `Skip` with that number.

**Comment by jba** [comment]
@vangent @shantuo @polinasok

**Comment by vangent** [comment]
We support pagination in `blob` using a [`PageToken`](https://github.com/google/go-cloud/blob/master/blob/driver/driver.go#L218). I think that would map onto docstore as follows:


* The `Query` struct returned from `Collection.Query` would include a `NextPageToken`. For `blob`, we used `[]byte` as the type, I think so that it could be serialized (as opposed to an `interface{}`).
* The `Query` request would have an operator to set the starting `PageToken`.

That looks pretty similar to what you have suggested above, just different names and possibly different types.

**Comment by jba** [comment]
Pagination is the wrong metaphor here. Pages are small but (from the user's POV) arbitrary-sized chunks that the system uses to break up a long stream of data. Here the user decides when to take the snapshot.

I don't think we want to put the `NextPageToken` on `Query`. After the user calls `Get` on the query to obtain an iterator, they forget about the query and just work with the iterator. That is the natural place to ask for the snapshot.

We don't want `NextPageToken` to be a field; it should be a method. It is relatively expensive to compute, so we want to build it on demand.

We could add a method to `Query` that accepts the token, but in my opinion that is more error-prone for this use case. You could build up that query in a different way from the original query, and that would probably give you useless results. The snapshot, on the other hand, includes the query, so it's impossible to make that mistake. If there are other use cases for starting at a particular point in the result set, then a `Query` method would make more sense.

**Comment by jba** [comment]
Here's my take on the difference between pagination in blob and this feature.

The blob API's pagination is designed to be a thin abstraction over the pagination features of the various services, to make it easy for drivers to expose the pagination portably. It's not for users; they never see pagination, just an iterator that always returns the next item.

By contrast, the query snapshot feature is designed to be as easy as possible for users. They can take the string from `Snapshot` and immediately put it in a form, then use the string to get the query back exactly where they left off.

**Comment by vangent** [comment]
Yes, I see. You are right, the pagination feature in `blob` is not exposed to the end user, it is used by the portable type + drivers. The user only sees an iterator.

IIUC, the feature you are suggesting here of taking a "snapshot" of the iterator so that it can be continued later could be applied to the `blob` iterator as well. Is that right?

A couple of questions:

1. Why can't this be done using `Where` and `Limit`? Paginated results on a web page are likely to be sorted by some key, so couldn't implement pagination be implemented something like:

```
page1Iter := c.Query().Where("Key", ">=", "").OrderBy("Key").Limit(101)
if page1Iter.Size() > 100 {
  page2Iter := c.Query().Where("Key", ">=", page[100].Key).OrderBy("Key").Limit(101)
}
```

etc.

2. For `Snapshot`, what semantics would you be able to provide portably? For example, what happens if documents are inserted "before" the `Snapshot` between when it is taken and when it is reconstituted? Would the behavior be consistent or would it vary between providers? (I'm guessing the latter, since I think I've heard you mention that one provider would implement this using a `SkipN`, while others are probably doing something like saving the current key).

**Comment by jba** [comment]
1. There are cases where `Where` can't restart in the same place, because the sort field is not unique. But perhaps those aren't interesting cases, and we can forget about them.

2. I was thinking that we wouldn't guarantee anything if the collection changed.

Since it's possible that using `Where` and `Limit` is good enough, let's not implement this. We'll keep the issue open so interested people can more easily discover it. We'll do it if we learn that there's a compelling reason for  it.

**Comment by jba** [comment]
Email from Marek Gilbert, a Firebase engineering lead:
> StartAt and endAt aren't really so much about query resumption as paging generally (next, previous, go back to page 2). We added it because we wanted to avoid users implementing paging using offsets, which don't work well in the mobile/disconnected context.

> For example, it's used in the Firebase console to implement an infinite scroll in the data viewer in a memory efficient way. Internally it's loading pages full of documents and as you scroll down earlier pages are dropped from memory but it does retain anchor documents for the unloaded pages. If you scroll backwards, the earlier pages can be reloaded using various combinations of the startAt-related calls.

**Comment by xuyang2** [comment]
FYI: https://docs.mongodb.com/manual/reference/method/cursor.skip/ says:
> The cursor.skip() method requires the server to scan from the beginning of the input results set before beginning to return results. As the offset increases, cursor.skip() will become slower.
