### ISSUE TITLE
docstore: support structs without a revision field

### ISSUE THREAD

**Issue by shantuo** [google/go-cloud#2308]
1. If I have a struct with a revision field, calling `Create` on it will fail. I think we should allow that since the user may want to use the same struct for other writes and want the revision check.
2. If I query a collection and get them into struct type without revision field, dynamo and mongo fails, I think this is a bug.

**Comment by jba** [comment]
> 1. If I have a struct with a revision field, calling `Create` on it will fail. I think we should allow that since the user may want to use the same struct for other writes and want the revision check.

You mean a non-nil revision field, right? I don't understand how that could be OK. This is supposedly a brand new document, so where did the revision field come from? 

_After_ the Create, the revision field will be populated, and then it will be used for later writes.

> 2. If I query a collection and get them into struct type without revision field, dynamo and mongo fails, I think this is a bug.

Yes. I planned on writing tests for structs with no revision field (and fixing those bugs). You can do it if you want.

**Comment by shantuo** [comment]
I was wrong on 1), that I used `string` for the revision, will do 2).

**Comment by jba** [comment]
@shantuo ping

**Comment by shantuo** [comment]
I noticed that we say "If a struct doesn't have a revision field, then no revision logic is performed." I think this difference between structs and maps may create confusion. For example, the user may have both maps and structs in their code and they don't have revision in any of them. The docstore package will perform revision logic on the map ones but no revision logic on the struct ones, which may cause some unintentional bugs. There are a couple of options:

1. We remove the default revision field, and only perform revision logic when the user specifies a revision key/field name on the collection. This means it will return an error if the struct doesn't have a revision field.
1. Keep what we say, and allow documents to be decoded into structs without a revision field.

**Comment by jba** [comment]
I don't like (1) because I think revision logic is important and we should do it wherever possible.

Maybe we could have an option to the constructor that allows the revision field to be missing. That way users will opt in to leaving out the revision processing.

**Comment by shantuo** [comment]
How about doing (2) plus an option on the collection, `DisableRevision`, which the user can use to opt out revision.

However, there still will be a change, which is we don't generate the revision string when there isn't a revision field in the struct type. WDYT? @jba @vangent

**Comment by vangent** [comment]
How about this:

1. Keep the default revision field, which the user can override using an `Option` (I think this means that every provider's `Options` struct needs it).
2. Apply revision logic for both maps and structs based on the revision field name. If a struct doesn't have the named field, it's an error.
3. Add a constant `NoRevisions` (or 'DisableRevisioning` or whatever); if the revision field is set to that constant, then don't do any revisioning logic for structs or maps.

Advantages:
* There's only a single `Option` instead of having to add a new one.
* The behavior is totally consistent between maps and structs.

The error message for a struct that doesn't have the named revision field could point the user at the constant if they just want to disable revisions.

**Comment by jba** [comment]
@vangent's plan SGTM.

There is still the question about whether we should maintain revisions on the backend. I think we should. That is, whenever we write a document, we should change the revision field of the _stored_ document, even if we can't check or change the field on the _local_ one. 

This will make the behavior more consistent across providers (since some update the revision automatically), and will also allow other readers of the same collection to use the full revision logic.

**Comment by shantuo** [comment]
@vangent using a single `Option` sounds better.

@jba I think we should maintain that on the backend. One scenario I was thinking about is that, if writer A put a document with revision into a collection, reader B tries to query them but doesn't have the revision field, should that be an error? I think the answer should be yes.

**Comment by jba** [comment]
> if writer A put a document with revision into a collection, reader B tries to query them but doesn't have the revision field, should that be an error? I think the answer should be yes.

It should be yes unless the user has opted into that behavior by setting the disable-revisions option.

**Comment by jba** [comment]
Our current thinking is this:

- Check the revision (perform optimistic locking) if and only if the argument document has a non-nil revision. In other words, the document must have a revision field and the value of that field must not be nil. (This is the current behavior.) 
- Write a revision if and only if the current document has a revision field.

`Query.Update` is a special case. It always does blind writes (after #2458) and it will take a boolean to indicate whether to write a revision.
