### ISSUE TITLE
all: consider adding a portable type for distributed lock/unlock services

### ISSUE THREAD

**Issue by omerlh** [google/go-cloud#2409]
Please use a title starting with the name of the affected package, or \"all\",
followed by a colon, followed by a short summary of the feature request.
Example: `blob/gcsblob: add support for more blobbing`.

### Is your feature request related to a problem? Please describe.

Azure support [leasing](https://docs.microsoft.com/en-us/rest/api/storageservices/lease-blob) operation that locks the blob. This is useful when handling concurrent requests to the blob, for example - when using Pulumi with Azure blob and running multiple operations in parallel.

### Describe the solution you'd like

Acquiring a lease before any operation to the blob and release it when the operation completes (Terraform does exactly that).

**Comment by vangent** [comment]
Hi @omerlh , thanks for the suggestion. Couple of questions:

1. Go CDK can only reasonable add features that are supported across providers. Do other providers (e.g., S3 and GCS, primarily) support similar functionality? I looked briefly and found reference to a "lock" for S3 and a "hold" for GCS, which may be similar but I'm not sure if the semantics are the same.

If the answer is "no", or until this feature is added, you can always use [`As` escape hatches](https://gocloud.dev/concepts/as/) to make provider-specific API calls like this. See [here](https://godoc.org/gocloud.dev/blob/azureblob#hdr-As) for the `As` escape hatches for `azureblob`.

2. Can you give a bit more detail about the use case? What is happening concurrently -- multiple writes, or a single write and multiple reads? One process, or multiple? If there are multiple writes, what would you want to happen to the writes that are blocked by the lease -- would they retry, or re-read the object, re-apply their changes, and retry, or ...? (IIUC, GCS uses revision numbers for this sort of thing rather than locks/leases).

**Comment by omerlh** [comment]
Pulumi is similar to terraform - it's infrastructure as code tool, allowing you to provision cloud resources with code. Without locking support, it is possible (although very rare) that multiple users will deploy changes to production affecting each other. The result can be very dangerous so this is why I'm asking.
I understand what I'm saying, so I'm ok with keeping this open for reference. I think it could be a good feature - having a "lock" feature, implemented using the different cloud implementations. I think a good start will be trying to lock before writing.

**Comment by vangent** [comment]
Interestingly, the [Terraform S3 backend](https://www.terraform.io/docs/backends/types/s3.html) uses DynamoDB for lock support; this implies to me that S3 doesn't support it natively, so a lock feature for `blob` is not going to be feasible.

The idea of a "lock" API with multiple implementations is reasonable though -- Azure Blob Storage would be one implementation, DynamoDB another, and there could also be SQL-based ones, etcd, GCS via conditional writes, Chubby.
