### ISSUE TITLE
docstore: allow some no field matching

### ISSUE THREAD

**Issue by Inuart** [google/go-cloud#2426]
### Describe the bug

We are unable to efficiently use `docstore/mongodocstore` for querying because `docstore`'s `DocumentIterator` checks that all map keys match the provided struct.

### To Reproduce

```
someStruct := struct {
		ID      string
		Name    string
		// Address string
	}{}
collection.Query().Get(ctx).Next(ctx, &someStruct)
```

Gets an error like `no field matching "address"`.

## Expected behavior

`go.mongodb.org/mongo-driver/mongo` iterators allows the use of a partial `*struct{}` too, but doesn't check if all fields match.

### Version

v0.15.1
here's the error line: https://github.com/google/go-cloud/blob/master/docstore/driver/codec.go#L663

**Comment by Inuart** [comment]
I just realized we can provide `FieldPath`s to `Get` to limit the projection to the required fields we need, so for me it seems that it's actually less of a problem.

**Comment by shantuo** [comment]
Hi, yes, you can pass in `FieldPath`s to get queries. Is there anything else you want to be fixed?

**Comment by Inuart** [comment]
Just an explanation as to why it's important for the library to have this behavior would be more than enough.

**Comment by jba** [comment]
The short answer is that it can lead to data loss.

Say you read a document into your struct, modify it, then write it back. If you didn't read a field, you won't write the field, and it will be gone, just as if you deleted it.

Maybe you have no intention of writing back the struct, but we don't know that, so we are playing it safe: if you read a document into a struct and there's a field missing in the struct, we return an error.

As you discovered, specifying the exact field paths you want is a workaround, probably the best one. If this turns out to be too much of a pain, we'd consider introducing a bool option (on the `mongodocstore.Options` struct) that would mean "I understand that dropping fields on read could lead to data loss, but I want to do it anyway." But that would be a fairly blunt instrument.

**Comment by jba** [comment]
By the way, we're glad that you're trying docstore, but curious how you managed to use it. It's not actually in a tagged release. Are you manually cloning the repo? In any case, we welcome your feedback.

**Comment by Inuart** [comment]
In that case I have to ask; is or will it be possible to update, let's say, only one field of all documents of a collection that follow a certain criteria at the same time and without having to fetch all of them previously?

For example, (partial)Update all docs that have `color = red` to have `color = blue`.

I'm not cloning the repo manually, I'm specifying `gocloud.dev/docstore/mongodocstore 1012b9d3127e` manually in the go.mod and the go tool does the rest.

**Comment by jba** [comment]
Yes, you'd write
```
err := coll.Query().Where("color", "=", "red").Update(ctx, docstore.Mods{"color": "blue"})
```
That will turn into a single `UpdateMany` call in MongoDB. (For other services, it may require fetching and updating each document individually.)
