### ISSUE TITLE
docstore: rename gcp and aws drivers to gcpfirestore and awsdynamodb

### ISSUE THREAD

**Issue by polinasok** [google/go-cloud#2427]
In the spirit of: https://github.com/google/go-cloud/blob/master/internal/docs/design.md#package-naming-conventions

**Comment by polinasok** [comment]
cc @vangent

**Comment by vangent** [comment]
After much discussion, let's go ahead with this rename.

The main advantages:

1. It makes it so that the actual product names are included in the package name, which will improve discoverability. E.g., we want a search for `firestore` on godoc.org to return our package somewhere in results.
2. It makes more clear which Cloud providers are associated with each package for users who are not familiar with the specific product names (e.g., GCP for Firestore). 3. It's more consistent with other APIs (e.g., `pubsub` and `secrets` packages don't all end with `pubsub` and `secrets` respectively, and do starts with `aws` or `gcp` or `azure`).

The main disadvantages are:

1. There's no `docstore` in the last section of the package name, so code that uses both our package and the native provider will have two names that are different but not necessarily obvious which is which (e.g., `gcpfirestore` and `firestore`).
2. We have to do the work to rename them.

I think the advantages outweigh the disadvantages, mostly because of advantage #1 above, and the fact that it's fairly trivial for users to alias their imports if they want to.

**Comment by shantuo** [comment]
Partially agree on 1) except for the example; godoc.org already returns our package for searching `firestore`, it does that by matching the `firestore` term in the package synopsys, and it actually does not match the partial `firestore` in `gcpfirestore`. But from the human side it does link the product with our driver more clearly.

**Comment by jba** [comment]
Shouldn't we also rename `mongodocstore` to `mongo`?

**Comment by vangent** [comment]
No, `mongodocstore` is fine, it's consistent with `kafkapubsub` for example, and it doesn't stutter. It "helps distinguish the package from the provider's own package name". We're not using `gcpfirestoredocstore` or `awsdynamodbdocstore` just because they are too long.

```
    *   May be omitted when it makes the package name too long (e.g. `awssnssqs`
        is long enough, don't add `pubsub`).
    *   Encouraged when it helps distinguish the package from the provider's own
        package name (e.g., `s3blob` not `s3`).
```
