### ISSUE TITLE
internal/website: add a check for broken links

### ISSUE THREAD

**Issue by jba** [google/go-cloud#2440]
We should occasionally check the website for broken links. That can be done with one command:
```
wget --spider -r -nd -nv -H -l 1 -w 2 -o wget.out https://gocloud.dev 
```
although we may need a larger value for `-l` (max crawl depth).

Source: https://www.digitalocean.com/community/tutorials/how-to-find-broken-links-on-your-website-using-wget-on-debian-7#step-2-%E2%80%94-running-wget.

**Comment by vangent** [comment]
This sounds like a good candidate to be added to `internal/testing/prereleasechecks.sh`.

**Comment by eliben** [comment]
I believe @zombiezen had a probe periodically checking that gocloud.dev is live. Perhaps it could be incorporated there too, somehow

(though adding to prereleasechecks sounds like a good low-cost solution)

**Comment by zombiezen** [comment]
Seems like a good idea, but worth noting:

-  Using the `{{<ref "...">}}` Hugo shortcode will automatically detect broken internal links.
-  The remaining links that would need to be checked would necessarily be external, thus making such a check not hermetic (unless we generated a "known links" list and compared against that).
-  Probers seem like not the best way to solve this, since we likely don't want someone to take immediate action if someone else's website goes out of date. I agree with @vangent, a pre-release check seems like the right approach, especially if we can make the check hermetic.
