### ISSUE TITLE
docstore: Query.Update should not do blind writes

### ISSUE THREAD

**Issue by jba** [google/go-cloud#2458]
The MongoDB implementation of `Query.Update` is a single RPC. It cannot check revisions. So `Query.Update` must always do blind writes. We need to document that, and make other drivers conform.

Other drivers run a query and update each returned document. A driver may retrieve the revision field in the query and then use it to construct the update, which would perform optimistic locking. They shouldn't do that.

**Comment by jba** [comment]
Some context: `Query.Update` is present specifically as a performance optimization for MongoDB, so we must make its semantics conform to MongoDB's implementation. We've already had a [feature request](https://github.com/google/go-cloud/issues/2426#issuecomment-506622077) for it (they didn't realize it already existed), which demonstrates that it's important, so we should not remove it.

**Comment by shantuo** [comment]
I think we should provide an option for the user to opt in using optimistic locking instead of always doing blind writes. Mongo is fine since it is one RPC and always succeeds, for the others, it might be better to consult the user. The option can be something like:

```go
type UpdateQueryOptions struct {
  Revision RevisionMode
}

type RevisionMode int

const (
  Unset RevisionMode = iota
  Disabled
  UpdateOnly
  CheckAndUpdate
)
```

I think the default should be `Unset` and returns an error since I don't think either of the other three could be a safe default. We don't want to put unexpected field to the user data and possibly cause an error when they read them, or leave the staled revision field unchanged when doing the update.

**Comment by jba** [comment]
> it is one RPC and always succeeds

It always succeeds because it does blind writes. I don't think it locks the collection, so you could clobber data if there were concurrent writes. That's my guess, based on the likely implementation.

If you want to do a query with update and check revisions, you can just write it out with a Query and calls to Update. That's the same thing we'd do in all implementations, anyway. I'm concerned that if we make it an option, then there will be a dramatic performance difference with mongo depending on the choice of option, and that won't be obvious to people.

I think the best solution is to just document carefully.

@eliben @polinasok thoughts?

**Comment by jba** [comment]
I was confused about this.

When you write
```
coll.Query().Where("Score", ">", 100).Update(ctx, docstore.Mods{"Score", 100})
```
I'm sure that MongoDB will atomically check, for each document, that Score is > 100 before setting it to 100. We should do the same in all drivers.

We already do it in `gcpfirestore`, thanks to [this line](https://github.com/google/go-cloud/blob/master/docstore/gcpfirestore/fs.go#L471). That performs the revision check, and the revision write is always done by Firestore.

For `awsdynamodb`, we don't know if the documents have revision fields. In fact, even within a single update query, some may have them and some may not. Since it's not an error to select a field that is not in the stored document, we can always select the revision field, and then look at the document to decide what to do: we perform a revision check and write if and only if the document has a revision.

So I don't think we need an option for this.

**Comment by shantuo** [comment]
I agree in general with one case that we will still need an option for whether or not updating the revision, since we don't know run a get query for MongoDB.

**Comment by jba** [comment]
Yes, good point.

Also, another point, which I thought I wrote before vacation but I guess I forgot: if you are doing an Update query without a `Where`, then you really are doing a blind write, and in that case we shouldn't do a revision check.

**Comment by jba** [comment]
> I agree in general with one case that we will still need an option for whether or not updating the revision, since we don't know run a get query for MongoDB.

What if we made this a mongo-specific collection option? Then we wouldn't have to clutter the portable API.

**Comment by jba** [comment]
I have a PR for this, which I'll mail after #2596.

**Comment by vangent** [comment]
A couple of thoughts:

My understanding from @shantuo is that the current idea is to make Query.Update (other than Mongo) query the service for documents matching the query, for the documentID and revisionID fields. The driver would then iterate over the resulting documents, creating an Update action for each, and then execute the action list. If the revisionID exists, then the driver would update the revision field for each document as part of each Update; this follows the pattern used elsewhere of letting the data tell us what to do. This seems reasonable to me, as does having a MongoDB-driver-specific option to tell us whether to do the revision update for MongoDB.

The question remains about whether to do revision **checks**. For example, imagine a Query.Update something like "increment the Count field for all documents with Count < 100". There are race conditions where a client could query for such documents, create an action list with increment actions, but meanwhile another client could have modified the Count field for some document(s) so that it is no longer < 100; those documents should not be updated.

We could follow the pattern from revision **updates** above, and let the data tell us what to do. I.e., if the Query returns a revisionID field, then do a revision precondition check as part of each generated Update action. This sounds OK, but my first impression was the returned error is not great for the user. They tried to do something that sounds like it should be an atomic operation, and got some kind of "revision mismatch" error for a subset of documents; maybe those documents should have been updated (i.e., Count was still < 100), or maybe they shouldn't have been. It's not clear how a user could deal with this.

One option might be to retry in the driver until revision precondition failures go away. For example, if the Query returned 100 documents, but the update on 3 of them failed with a precondition error, we could re-issue the original query with an additional filter that the documentID be one of those 3 (I'm not sure this is possible). Or, re-issue the original query 3x, once for each retry, if Query doesn't support "IN". Keep redoing this until all of the Updates are done (or until the Query doesn't return anything, indicating that that document doesn't match the Query anymore).

Separately, and this is somewhat independent of the specific issue of blind writes for Query.Update, but tangentially maybe relevant, could the Query+Update for non-MongoDB drivers be implemented in the portable type instead of in each driver? I.e., the `driver` interface would have a function that returns a boolean indicating whether it has an optimized Query.Update; only `mongodocstore` would return true from that function; the portable type would call the driver Query.Update function if that function returned true, else it would implement Query.Update using Query and Actions.

**Comment by jba** [comment]
> if the Query returns a revisionID field, then do a revision precondition check as part of each generated Update action

Agreed, unless there are no filters in the query.

> re-issue the original query with an additional filter that the documentID be one of those 3

Or we could do a batch get on those documents. We have their keys.

> could the Query+Update for non-MongoDB drivers be implemented in the portable type instead of in each driver?

Yes, I'm pretty sure it could.

**Comment by jba** [comment]
Decided:
- OK to do a blind update if there are no Where clauses.
- OK for Mongo driver to have a collection option to write revision fields on update.
- Query.Update needs to retry on revision check failure: #2611
- Look into moving the non-Mongo update loop into the portable type: #2612
