### ISSUE TITLE
pubsub/awssnssqs: JSON messages aren't working.

### ISSUE THREAD

**Issue by wedneyyuri** [google/go-cloud#2459]
### Describe the bug

JSON messages are being received as empty strings.

### To Reproduce

- Create a new queue.
- Send any example message to the queue (`{ "hello": "world" }`)
- The following code will output `Got message ''`

```golang
package main

import (
	"context"
	"fmt"
	"time"
	"github.com/pkg/errors"
	"gocloud.dev/pubsub"
	_ "gocloud.dev/pubsub/awssnssqs"
)

const subscriptionURL = "awssqs://sqs.us-east-1.amazonaws.com/99999999/example-queue"

func execute() error {
	subscription, err := pubsub.OpenSubscription(context.Background(), subscriptionURL)
	if err != nil {
		return errors.Wrap(err, "open subscription")
	}

	ctx := context.Background()
	for {
		message, err := subscription.Receive(ctx)
		if err != nil {
			return err
		}
		fmt.Printf("Got message '%v'\n", string(message.Body))

		fmt.Println("Sleeping for 5 seconds...")
		<-time.After(5 * time.Second)
	}
}

func main() {
	if err := execute(); err != nil {
		panic(err)
	}
}

```

## Expected behavior

Raw Messages (as using any SQS client)

### Version

v0.15.0

**Comment by wedneyyuri** [comment]
The issue seems to be here:

https://github.com/google/go-cloud/blob/9b5268f0a2b98af6ac6714a0013f9ccd264b1606/pubsub/awssnssqs/awssnssqs.go#L604

Which isn't always true.

![image](https://user-images.githubusercontent.com/7511692/60613164-b2b44e80-9da0-11e9-9d12-6a0c34ddfa35.png)

**Comment by vangent** [comment]
Thanks for the report. I've confirmed this is an issue and am adding a test for it.

It's not obvious if there's a reliable way to tell when the message arrives whether it is a "raw" message or not.

* If there are top-level attributes, it is definitely raw, but that doesn't work if there aren't any attributes on the message.
* Parsing the body as JSON isn't useful since the raw message could be JSON as well.
* We could check for specific fields in the parsed JSON but that sounds flaky as well.

My tentative plan is to add a field to `SubscriberOptions` which lets the user tell us whether to read raw or not, with the default value being `Unknown`, in which case we'll do our best to figure it out (but will likely be inefficient due to sometimes needing to try to parse the body as JSON).
