### ISSUE TITLE
all: AWS SDK v2 profile support

### ISSUE THREAD

**Issue by kaihendry** [google/go-cloud#259]
Hi, I am [familiar](https://github.com/kaihendry/goserverless.sg/blob/master/main.go#L99) with using something like:

    cfg, err := external.LoadDefaultAWSConfig(external.WithSharedConfigProfile("my-aws-profile"))

To setup my AWS credentials from my local environment using https://github.com/aws/aws-sdk-go-v2/ of AWS's API. I am not sure how to map this onto your `sess client.ConfigProvider`. I think v2 completely does away with sessions for example.
http://talks.webconverger.com/2018-01-25/#10

**Comment by zombiezen** [comment]
IIUC AWS SDK v2 is still in [developer preview](https://aws.amazon.com/blogs/developer/aws-sdk-for-go-2-0-developer-preview/). As such, we've stuck with the 1.0 version since that's what most people are still using. See b68c9d772985a6f715cd7e698156a0a12f1d3ace for one place where we migrated to be consistent.

We should think about what the interoperability story is with AWS v2, but I'm not clear reading from their docs what the migration strategy is.

**Comment by vangent** [comment]
See #3026.
