### ISSUE TITLE
docstore: support OR queries

### ISSUE THREAD

**Issue by Inuart** [google/go-cloud#2616]
Currently docstore only supports AND queries.

Suppose we want to query for documents that have `status=A OR status=B`. To achieve that OR query in mongo we can write `bson.M{"status":bson.M{"$in": []string{"A", "B"}}}`, but it's not clear if it can currently be done in docstore in a portable way.

The suggestion given in #1769 is to run 2 separate queries, fetching the results that have `status=A` and then the ones that have `status=B`.

I think this workaround does not really work in some cases. For example, if the `status` is updated by other services between the execution of the two queries, as is our case.

This can result in either getting duplicate documents if the `state` transitions from `A` to `B`, or not getting enough documents if it transitions from `B` to `A`, or both.

So the workaround we are using is to fallback to mongo for any OR query we need to do.

**Comment by vangent** [comment]
As discussed on #1769, we can't support this in a portable way since some providers don't support an `OR` operation.

One workaround would be to make two queries and merge them, which isn't transactional; we'd rather not do that internally to make it look like `OR` is a portable feature, because as observed above the semantics are different.

The other workaround if your backend is a service that *does* support `OR` (like MongoDB) is to use `As` to get access to the underlying type and issue the query directly ([example](https://godoc.org/gocloud.dev/docstore#Collection.As)).
