### ISSUE TITLE
blob: support PUT method for signed url

### ISSUE THREAD

**Issue by shouichi** [google/go-cloud#2625]
### Is your feature request related to a problem? Please describe.

We need to return a signed url that allows end user to directly upload a file to cloud storage. AFAK, cloud storage and s3 support the feature (allowing end user to send PUT/DELETE requests). 

### Describe the solution you'd like

Allow `blob.SignedURLOptions`  to specify HTTP method.

**Comment by vangent** [comment]
Taking a look....

**Comment by vangent** [comment]
I have been looking into this. It seems mostly possible; the main wrinkles I've run into are:

1. Azure Blob Storage doesn't quite support what we need. You can create a SAS token that will work with `PUT`, but they [require](https://stackoverflow.com/questions/37824136/put-on-sas-blob-url-without-specifying-x-ms-blob-type-header) that an Azure-specific header (`x-ms-blob-type`) be included in the `PUT`, which makes it non-portable.

2. The conformance tests are not as strict as I'd like, because at least some providers appear to allow you to do operations with a signed URL for one method using a different method. For example, GCS will let you do a `PUT` with a signed URL you created for `GET`, as long as the client making the request has write access. Since our driver tests use record/replay and the HTTP client needs full authorization, this means it's not easy to write tests that verify that signed URLs are only usable for the operation they were created for.

**Comment by shouichi** [comment]
Thank you for your time and effort of looking into details. Great to hear that it is possible and I understand the limitations. Is there any way I can help?

**Comment by vangent** [comment]
I said "mostly possible", which is not the same as "possible" :-|. In particular, #1 above is definitely problematic; it makes it impossible to implement this feature for `PUT` in a portable way. If you can find a way around it that would be helpful!

In the short term, you can use `As` functions to access this functionality in a service-specific way. For example, if you are using S3, the code would look something like this:

```
// import "github.com/aws/aws-sdk-go/aws"
// import "github.com/aws/aws-sdk-go/service/s3"

func getPresignedURLForPUT(bucket *blob.Bucket, bucketName, blobKey string, expiry time.Duration) (string, error) {
  var client *s3.S3
  if bucket.As(&client) {
    // It's an AWS S3 bucket.
    in := &s3.PutObjectInput{
      Bucket: aws.String(bucketName),
      Key:    aws.String(blobKey),
    }
    req, _ := client.PutObjectRequest(in)
    return req.Presign(expiry)
  }
  // Handle other driver types if needed....
  return "", errors.New("not supported")
}
```

Hope that helps!

**Comment by vangent** [comment]
FYI, I sent a PR to support this, with a hack to work around the Azure issue.

**Comment by shouichi** [comment]
Thank you :)
