### ISSUE TITLE
blob: Allow access to URLSigner for fileblob

### ISSUE THREAD

**Issue by tamalsaha** [google/go-cloud#2629]
I am using SignedURL method with fileblob and now I want to server that file as shown here:
https://github.com/google/go-cloud/blob/51225688efc044bd3c1c7f476c24a1c8b74f9e12/blob/fileblob/fileblob_test.go#L70

The problem is that there is no way access the URLSigner created here: https://github.com/google/go-cloud/blob/51225688efc044bd3c1c7f476c24a1c8b74f9e12/blob/fileblob/fileblob.go#L144

I would prefer to not copy the url parsing code from this function. So, can you allow us to access the URLSigner ?

**Comment by vangent** [comment]
It's not obvious how we could make the `URLSigner` created by the default `URLOpener` accessible. The only object you have after calling `blob.OpenBucket` is a `*blob.Bucket`, which isn't even `fileblob`-specific. Do you have a suggestion for how we could do it?

Some other options for you include:

1. You could use the [`fileblob` constructor](https://godoc.org/gocloud.dev/blob/fileblob#OpenBucket) instead of using a URL. You can pass your own `fileblob.URLSigner` in the `Options`.

2. You could create your own [`fileblob.URLOpener`](https://godoc.org/gocloud.dev/blob/fileblob#URLOpener), setting your own `fileblob.URLSigner` in its `Options` (`fileblob.URLSignerHMAC` implements `fileblob.URLSigner`). Then your URL won't need to have `base_url` or `secret_key_path` either. Once you have a custom `URLOpener`, you can either:
  a. call `OpenBucketURL` directly on it with your URL.
  b. create a new `blob.URLMux` and register your custom `fileblob.URLOpener` on it along with whatever other openers you need, and then call `OpenBucket` on the mux; see https://gocloud.dev/concepts/urls/#muxes.

3. You can recreate the `URLSignerHMAC` in you serving code by calling `NewURLSignerHMAC` yourself. Depending on how you set up your configuration, you could get the `baseURL` and `secretKeyPath` by parsing the `fileblob` URL as you noted, or by configuring those separately.

Hope that helps!
