### ISSUE TITLE
all: Improve testability by adding test (eg. in memory) operations

### ISSUE THREAD

**Issue by Draal** [google/go-cloud#269]
To make easier  integration testing it would be great to have in memory/mock implementations of
binary (blob) storage, mock mysql driver and the other services which will be added in the feature.

**Comment by shantuo** [comment]
We use replay test in `internal/testing`. The tests run in replay mode unless a `--record` flag is passed to update the record. We do lack some tests not converted to use it. (e.g. blob/gcsblob #18 ) All future tests should use this package. I'm closing this issue for now since the leftover is tracked already. Feel free to reopen if there is more to discuss.

**Comment by zombiezen** [comment]
@Draal, are you talking about testing from the standpoint of using Go Cloud or developing it? I interpreted it as the former, but I think @shantuo interpreted it as the latter.

**Comment by zombiezen** [comment]
You can use [`blob/fileblob`](https://godoc.org/github.com/google/go-cloud/blob/fileblob) and [`runtimevar/filevar`](https://godoc.org/github.com/google/go-cloud/runtimevar/filevar) as fakes. `server` can be used with default options for local development and you can connect to an ordinary MySQL database for the rest.

**Comment by zombiezen** [comment]
Closing this out since I haven't seen any response in a couple weeks. @Draal, feel free to open another issue if you have more ideas on testing.
