### ISSUE TITLE
pubsub/gcppubsub: add support for GCP pubsub emulator

### ISSUE THREAD

**Issue by rajveermalviya** [google/go-cloud#2694]
### Is your feature request related to a problem? Please describe.

Because the endpoint is [hardcoded](https://github.com/google/go-cloud/blob/7c891ceb5d843ae23f755a4e7bc42cd3f4a48660/pubsub/gcppubsub/gcppubsub.go#L74), the GCP pubsub driver cannot be configured to connect to the emulator.

### Describe the solution you'd like

Adding an option to connect to the emulator would be helpful.

### Additional context

It is important to be able to test the applications using the pubsub emulator.

**Comment by vangent** [comment]
You might also be able to test your application using another local provider, e.g., `mempubsub` or `rabbitpubsub`. That said, this is a reasonable request.

Since the main GCP pubsub [constructor](https://github.com/google/go-cloud/blob/7c891ceb5d843ae23f755a4e7bc42cd3f4a48660/pubsub/gcppubsub/gcppubsub.go#L246) takes a `*raw.PublisherClient`, and you [get](https://github.com/google/go-cloud/blob/7c891ceb5d843ae23f755a4e7bc42cd3f4a48660/pubsub/gcppubsub/gcppubsub.go#L230) one of those by providing a `*grpc.ClientConn`, I think this is just a matter of adding a new [DialEmulator](https://github.com/google/go-cloud/blob/7c891ceb5d843ae23f755a4e7bc42cd3f4a48660/pubsub/gcppubsub/gcppubsub.go#L217) function.

An optional addition would be to add support for an environment variable (probably `PUBSUB_EMULATOR_HOST` as suggested in https://cloud.google.com/pubsub/docs/emulator) that would force use of `DialEmulator` instead of the normal `Dial` in the [default URL opener](https://github.com/google/go-cloud/blob/7c891ceb5d843ae23f755a4e7bc42cd3f4a48660/pubsub/gcppubsub/gcppubsub.go#L120).
Do you mind sending a PR? I can review it.
