### ISSUE TITLE
blob: more "go-like" ListIterator

### ISSUE THREAD

**Issue by mbyio** [google/go-cloud#2699]
### Is your feature request related to a problem? Please describe.

I'm using the blob List functionality, but it returns an iterator that is a little awkward to use.

In the standard library, we see two examples of iterators: https://golang.org/pkg/database/sql/#Rows and https://golang.org/pkg/bufio/#Scanner. To use them, you structure a loop like so (pseudocode):

```go
for scan.Next() {
    scan.GetNextItem()
}
if scan.Err() {
    // handle error
}
```

The ListIterator, on the other hand, forces you to write a loop with breaks and extra, confusing error handling:

```go
for {
    item, err := iter.Next(ctx context.Context)
    switch err {
    case io.EOF:
        break
    case nil:
        // use the item
    default:
        // in the default case, handle the error; weird!
}
```

With this pattern, you have to handle `io.EOF`, even though we aren't doing IO (at least, not directly) and it isn't an actual error, and we have to write this sort of deeply nested code in a switch or `if.. else if.. else` statement, which is awkward to write and read.

### Describe the solution you'd like

Switch to use the more standard iterator pattern. The main disadvantage as far as I can see is you can't pass a separate context for each call - but I'm not sure why you would want to do that. You don't even know if it is making a network call, so it doesn't really make sense to have a separate context each time. Not specifying a context for each call would also make this match up better with other blob functionality. Writers and Readers in this package use one context for their whole lifetimes, for example.

### Describe alternatives you've considered

It looks like this project is not at 1.0 yet, and I believe you can make this change without breaking. (by just adding the functionality). But, if you don't want to make the change, it would be nice to give people an example of how to write an appropriate `for` loop.

### Additional context

**Comment by vangent** [comment]
Having a separate context per call is definitely desirable; we weren't able to do that for `Reader` and `Writer` because we wanted to implement the standard interfaces, which sadly predated context (although see https://github.com/golang/go/issues/20280).

Unfortunately, we're at the point where we have a fair number of users and don't want to break them unless absolutely necessary. I frankly don't recall whether we considered the iterator style you reference and rejected it for some reason (maybe being able to pass a context?), but we're unlikely to change it at this point. I'll add it to our unplanned backlog in case we get a lot of pushback on that.
