### ISSUE TITLE
blob/s3blob: Allow MetadataDirective to be set for S3 Copy

### ISSUE THREAD

**Issue by Qinusty** [google/go-cloud#2710]
I am currently unable to make use of the Copy function when the goal is to force a metadata REPLACE. In the S3 api CLI this is performed through `--metadata-directive "REPLACE"`. In the underlying s3 library used here, it can be performed through `CopyObjectInput.SetMetadataDirective("REPLACE")`.

### Describe the solution you'd like

It should be possible to specify a metadata directive for copy commands to allow for more flexible copy operations.

I have dived into trying to solve this problem but haven't figured out how to make this change without being intrusive towards the generic nature of the blob implementations.

**Comment by vangent** [comment]
The functionality you describe is not generic (i.e., it does not make sense to expose in `blob` itself, since it's S3-specific). To access provider-specific functionality, you should use `As`:

* https://gocloud.dev/concepts/as/
* You'll need to set `CopyOptions.BeforeCopy` (https://godoc.org/gocloud.dev/blob#CopyOptions) 
* Inside your `BeforeCopy` function, call the `asFunc` with a `***s3.CopyObjectInput` (https://godoc.org/gocloud.dev/blob/s3blob#hdr-As).

**Comment by vangent** [comment]
Here's an example using `WriterOptions.BeforeWrite` against a GCS driver, but the basic idea should be similar:
https://github.com/google/go-cloud/blob/master/blob/example_test.go#L319
