### ISSUE TITLE
blob: Redis based blobstore

### ISSUE THREAD

**Issue by tamalsaha** [google/go-cloud#2724]
Please use a title starting with the name of the affected package, or \"all\",
followed by a colon, followed by a short summary of the feature request.
Example: `blob/gcsblob: add support for more blobbing`.

### Is your feature request related to a problem? Please describe.

We would like to use in-memory blob store but something shared across all the Kubernetes replicas of my micro-service.

### Describe the solution you'd like

A blob store interface which stores data in Redis with LRU or time based eviction.

### Describe alternatives you've considered

Write my own caching interface.

**Comment by shidel-dev** [comment]
I'm not sure redis is very suited for this task. The existing backends do not have limits on the max value size. redis is limited to `512 MB`. I pretty sure that multipart uploads would be quite strange to implement as well.

Wouldn't it be better to treat redis as a cache, instead of pretending it is a blob store.

It might be better to have a cloud agnostic cache api, as part of go-cloud. This is something I  have been thinking about some.

**Comment by rusenask** [comment]
:+1:  for cache API, I come here every few months to check whether anyone started "cache" interface as it would be really useful :) Initially it could just be redis/memcache/whatever and then we could expand it.

**Comment by vangent** [comment]
#2623 is the feature request for a caching api.
