### ISSUE TITLE
blob/s3blob: Support custom HTTP client for AWS SDK

### ISSUE THREAD

**Issue by richardartoul** [google/go-cloud#2748]
# Is your feature request related to a problem? Please describe.
The AWS S3 SDK uses *http.DefaultClient by default, however, for high throughput use-cases users may want to tune some of the settings on the http client (the HTTP transport buffer size and number of idle connections per host, for example among other things).

The current implementation of this library supports this, but only if I fallback to using the S3 constructor manually which means I have to manage my own bucket accessors.

It would be nice if there was some way I could specify the HTTP client that I would like the s3 implementation to use whenever it creates a new session so I don't have to manage region configuration and all that on my own.

I'm happy to do the implementation work here I'm just not sure what would be the best interface (package level function that sets a global?)

### Describe the solution you'd like

I'm happy with any interface that lets me configure the HTTP client for the S3 implementation while still using the "abstracted" bucket-oriented API. Its not clear to me what the best way to do that is (although I suggested a package level function that sets a global above I'm not sure if its the best approach).

### Describe alternatives you've considered

The current alternative is to use the S3 constructor manually which defeats the purpose of using a library like this.

### Additional context

N.A

**Comment by vangent** [comment]
> only if I fallback to using the S3 constructor manually which means I
> have to manage my own bucket accessors

Can you clarify what you mean by this?

If you're using the `s3.OpenBucket` [constructor](https://gocloud.dev/howto/blob/#s3-ctor), you can pass it an `aws.Session`, which can include a custom `HTTPClient` (https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config.WithHTTPClient). After that you can use the returned `blob.Bucket` and its methods.

If you're using the `blob.OpenBucket` API to open a `Bucket` using a URL (https://gocloud.dev/howto/blob/#s3), we only support a limited set of URL parameters, described here (https://godoc.org/gocloud.dev/aws#ConfigFromURLParams).

So, it's possible that you will need to use the explicit constructor instead of the URL-based one.

https://docs.aws.amazon.com/sdk-for-go/api/aws/ (search for "SDK Default HTTP Client") also implies that you can modify `http.DefaultClient` and have it take effect globally, ("This means that if the http.DefaultClient is modified by other components of your application the modifications will be picked up by the SDK as well"), but doesn't recommend it.

HTH
