### ISSUE TITLE
blob/gcsblob: BeforeWrite asFunc call order has affect

### ISSUE THREAD

**Issue by wader** [google/go-cloud#2760]
# Describe the bug

The order which `asFunc` is called to get `*storage.Writer` and `**storage.ObjectHandle` seems to have affect.

### To Reproduce

```go
package main

import (
	"context"
	"log"

	"cloud.google.com/go/storage"
	"gocloud.dev/blob"
	_ "gocloud.dev/blob/gcsblob"
)

func main() {
	// change this
	bucketURL := "gs://test"
	blobKey := "test"
	encryptionKey := make([]byte, 32)

	bucket, err := blob.OpenBucket(context.Background(), bucketURL)
	if err != nil {
		panic(err)
	}

	var writerOpts *blob.WriterOptions
	writerOpts = &blob.WriterOptions{
		BeforeWrite: func(asFunc func(interface{}) bool) error {
			var gcsObjectHandler **storage.ObjectHandle
			var gcsWriter *storage.Writer

			asFunc(&gcsWriter)

			if asFunc(&gcsObjectHandler) {
				*gcsObjectHandler = (**gcsObjectHandler).Key(encryptionKey)
			}

			// If called after instead it works
			//asFunc(&gcsWriter)

			return nil
		},
	}

	blobWriter, err := bucket.NewWriter(context.Background(), blobKey, writerOpts)
	if err != nil {
		panic(err)
	}
	blobWriter.Close()

	readerOpts := &blob.ReaderOptions{
		BeforeRead: func(asFunc func(interface{}) bool) error {
			var o **storage.ObjectHandle
			if asFunc(&o) {
				*o = (**o).Key(encryptionKey)
			}

			return nil
		},
	}
	blobReader, err := bucket.NewReader(context.Background(), blobKey, readerOpts)
	if err != nil {
		panic(err)
	}
	blobReader.Close()
}

```

```sh
r$ go run gcsblob_beforewrite_asfunc_order.go
panic: blob (key "test") (code=Unknown): googleapi: got HTTP response code 400 with body: <?xml version='1.0' encoding='UTF-8'?><Error><Code>ResourceNotEncryptedWithCustomerEncryptionKey</Code><Message>The resource is not encrypted with a customer encryption key.</Message><Details>The requested object is not encrypted by a customer-supplied encryption key.</Details></Error>

goroutine 1 [running]:
main.main()
	/Users/wader/src/gosal/repro/gcsblob_beforewrite_asfunc_order.go:57 +0x2d7
exit status 2
```

## Expected behavior

That the key is used when writing the blob.

### Version

v0.19.0

### Additional context

Now when poking around in the gcsblob code a bit i noticed that there is an explicit check if the writer has been created or not before returning the ObjectHandle at https://github.com/google/go-cloud/blob/master/blob/gcsblob/gcsblob.go#L516

So i guess there is a good reason for this? is it documented somewhere?

I noticed this when implementing a service that is suppose to be compatible with another service that write gcs blobs with case sensitive metadata keys (need writer to mess with the metadata keys) and uses encryption keys.

**Comment by vangent** [comment]
If I recall correctly, the `storage.ObjectHandle ` is used to create the `storage.Writer`. The `**storage.ObjectHandle` for `BeforeWriter` is a double pointer, so it can be replaced by the caller; that's why the `Writer` is made lazily. There's a comment about this here:
https://github.com/google/go-cloud/blob/master/blob/gcsblob/gcsblob.go#L496

and an example using `ObjectHandle.If` to apply a condition and replace the previous `ObjectHandle` here:
https://github.com/google/go-cloud/blob/master/blob/gcsblob/gcsblob_test.go#L374

So yes, if you want to also use `BeforeWrite` to access the `storage.Writer`, you need to do that *after* accessing the `storage.ObjectHandle`. Calling `BeforeWrite` with a `storage.Writer` forces the `Writer` to be created, and after that fetching the `storage.ObjectHandle` will fail.

I'll send a PR to update the documentation to make the ordering requirement more clear.

**Comment by vangent** [comment]
https://github.com/google/go-cloud/pull/2761

**Comment by wader** [comment]
Thanks! that make sense. Now when i think about it would be hard or impossible to recreate the writer in a sane why if it should keep the customisations that has been made?
