### ISSUE TITLE
blob: add support for GCS via Firebase

### ISSUE THREAD

**Issue by tooolbox** [google/go-cloud#2862]
### Is your feature request related to a problem? Please describe.

I am using the [Go Firebase Admin SDK](https://github.com/firebase/firebase-admin-go) in my service.  Up until now it has mainly been used for Auth.  Now I would like to use it for blob storage; Firebase conveniently allows you to access GCS buckets using your existing credential set.  (Awesome!)  At the same time, I would like to use the Go CDK to abstract this blob storage so I can for example use flatfile for local development.

### Describe the solution you'd like

Ideally I could use the `blob` package to open a GCS bucket using Firebase credentials.

Right now I do this:

```go
opt := option.WithCredentialsFile("~/my-credentials.json")
firebaseApp, _ := firebase.NewApp(context.Background(), nil, opt)
storage, _ := firebaseApp.Storage(context.Background())
bucket, _ := storage.Bucket("my-bucket")
```

But ideally I could do this:

```go
bucket, _ := blob.OpenBucket(ctx, "fb://my-bucket")
```

### Describe alternatives you've considered

1. I can implement my own abstraction for blob storage.
2. Perhaps I could set my Firebase admin key as `GOOGLE_APPLICATION_CREDENTIALS` and just open `gs://my-bucket`, but I have found no documentation that indicates this is possible.

**Comment by vangent** [comment]
Can you try 2) ?

From a quick glance, [firebase.Storage](https://github.com/firebase/firebase-admin-go/blob/master/firebase.go) just creates a `storage.Client` the same way that Go CDK does, and (firebase App](https://github.com/firebase/firebase-admin-go/blob/master/firebase.go#L96) just calls [firebase.Storage` with whatever client options you passed when you created the App. The only tricky business is how it can load config defaults for Firebase (https://github.com/firebase/firebase-admin-go/blob/master/firebase.go#L167).

 Unfortunately the firebase packages do not expose anything like the `storage.Client` or the config options it computes so that kinds of limits the options in terms of starting things off with `firebase` code and then converting to a Go CDK `blob.Bucket`.

If you can figure out how to get the `google.Credentials` for your firebase account, you should be able to create a `gcp.TokenSource` (https://github.com/google/go-cloud/blob/master/gcp/gcp.go#L88) and from there a `gcp.HttpClient` (https://github.com/google/go-cloud/blob/master/gcp/gcp.go#L58) that you can use to create a `blob.Bucket` (https://github.com/google/go-cloud/blob/master/blob/gcsblob/gcsblob.go#L313).

If you can figure out a reasonable way to get Firebase creds and you want to use the default `URLOpener` you could send a PR to update it, somewhere around [here](https://github.com/google/go-cloud/blob/master/blob/gcsblob/gcsblob.go#L158).

**Comment by emcfarlane** [comment]
I think you can use the gs bucket URL directly: `gs://{projectID}.appspot.com`. If you need to run the emulators locally you will have to set the environement:
```go
	os.Setenv("FIREBASE_STORAGE_EMULATOR_HOST", "localhost:9199")
	os.Setenv("STORAGE_EMULATOR_HOST", "localhost:9199")
```
One to configre firebase, the other to configure go cloud blob. I think the behaviour of the firebase emulator is limited tho. Getting an error:
```
Error in : blob (code=NotFound): storage: bucket doesn't exist
```
on trying to List with a Delimiter and Prefix options set. Works fine on the real implementation.

**Comment by emcfarlane** [comment]
Filed a bug here: https://github.com/firebase/firebase-tools/issues/5129
