### ISSUE TITLE
blob/s3: allow to specify profile via query string

### ISSUE THREAD

**Issue by ekini** [google/go-cloud#2865]
### Problem

It would be nice to be able to specify AWS profile via query string, like `?profile=my_profile`.

At the moment the only possible way to do it is via an env var `AWS_PROFILE` (or `AWS_DEFAULT_PROFILE`), which is very inconvenient and doesn't work well if you have multiple AWS accounts and multiple projects.

### Solution

It won't require any SDK updates, just a couple of code changes.
As per [the doc](https://docs.aws.amazon.com/sdk-for-go/api/aws/session/), it will need `Profile: xxx` [here](https://github.com/google/go-cloud/blob/master/aws/aws.go#L41).

The profile can be parsed in [here](https://github.com/google/go-cloud/blob/master/aws/aws.go#L81) with renaming the `ConfigFromURLParams` function to something more appropriate like `SessionFromURLParams` .

I'd be keen to make a PR if the idea sounds good.

**Comment by thisisaaronland** [comment]
FWIW, this is also a feature I would like to see added to the various AWS packages.

I've "rolled my own" for the S3 blob package which is not at all elegant, and is little more than a thin wrapper around the existing S3 constructor, but gets the job done:

* https://github.com/aaronland/go-cloud-s3blob

Under the hood it uses a separate helper package for constructing AWS sessions from DSN strings:

* https://github.com/aaronland/go-aws-session

I am not suggesting that the Go Cloud use either of these packages but including them as references and to second @ekini 's request.

**Comment by vangent** [comment]
A PR for this sounds fine.

Note however that `aws.ConfigFromURLParams` is public, so we can't rename it without breaking backwards compatibility.

Also, today I think we only ever create one session:
https://github.com/google/go-cloud/blob/master/blob/s3blob/s3blob.go#L107

so that might require some re-thinking if there's a URL parameters that needs to be passed to `NewDefaultSession`.

I suggest trying a PR that updates `s3blob` first, it can then be applied to other S3 drivers in a second PR once we've decided on an approach.
