### ISSUE TITLE
blob/fileblob: SignedURL returns an errors.New instead of gcerr.Error with code Unimplemented when URLSigner is not set

### ISSUE THREAD

**Issue by segevfiner** [google/go-cloud#2867]
### Describe the bug

When you call `bucket.SignedURL` with the fileblob driver without URLSigner set, you receive back an plain `errors.New` error:
https://github.com/google/go-cloud/blob/6be5a462804a1e9eb8bd63feb2d14f7aac068b0c/blob/fileblob/fileblob.go#L652

Instead of a `gcerr.Error` with code `Unimplemented` as the API is documented to return. This makes code that degrades gracefully when `SignedURL` is not supported to fail without explicitly checking for this error. Though just returning `Unimplemented` can make it difficult for someone to figure out that he can set `URLSigner` unless the error also includes a message to such an effect in addition to the error code.

### To Reproduce

```go
blob.OpenBucket("file:///some_path").SignedURL(context.Background(), "key", nil)
```

## Expected behavior

It returns a `gcerr.Error` with code `Unimplemented`.

### Version

v0.20.0

### Additional context
Go 1.15.2 using Go modules.

**Comment by vangent** [comment]
Hm, interesting. The `SignedURL` API currently returns `Unimplemented` for drivers that don't support the requested functionality (e.g., `memblob` does this). The driver tests verify this. `fileblob` is different in that it does support `SignedURL`; the error is because it hasn't been configured correctly to do so. A couple of other drivers do this as well.

IMHO it's arguable whether `Unimplemented` is the right error; it could be misleading if the misconfiguration is not on purpose. But, probably the best of both worlds is to return the `Unimplemented` error code along with a message.

**Comment by segevfiner** [comment]
Maybe a note to that effect should be added to the docs of `SignedURL` that says that `Unimplemented` is returned also in the case the driver isn't configured properly to support it but otherwise can, and not only in the case the driver doesn't support it at all?
