### ISSUE TITLE
blob: Add/Expose ListPaged in blob.Bucket

### ISSUE THREAD

**Issue by segevfiner** [google/go-cloud#2880]
### Is your feature request related to a problem? Please describe.
When listing buckets contents in a web services, it is common/imperative to do so as a paginated API when the buckets can be big so as not to run out of memory or return a huge response all at once. To do so, you need an API that allows you to page through the results manually with the underlying pagination mechanism of the object/blob store. Often a keyset pagination where you set the size of the page and get a key to be passed to the next call to get the next one.

This exists in the underlying blob driver as `ListPaged` and is wrapped by `List` to provide an API that iterates through the pages for you, but `ListPaged` itself is not exposed in the `blob.Bucket` interface to be used in the scenario you want to paginate by yourself.

### Describe the solution you'd like
Expose a `ListPaged` method in `blob.Bucket` that allows the application to manage pagination by itself.

### Describe alternatives you've considered
Not using the package for listing buckets. Trying to use the underlying blob driver interface directly (But the package purposefully makes this difficult)

### Additional context
https://pkg.go.dev/gocloud.dev/blob#Bucket.List
vs
`ListPaged` in https://pkg.go.dev/gocloud.dev@v0.20.0/blob/driver#Bucket

**Comment by vangent** [comment]
It turns out this is complicated. We originally had a paginated API in blob.Bucket, but removed it because the semantics varied across providers in terms of what they offer (notably for consistency -- what happens if a new blob is inserted/deleted on page 1 after you request before you request page 2?). From what we've seen, most devs who need this type of functionality build a secondary index in a more strongly consistent datastore (e.g., a SQL database with a table containing the keys, or something like that).

If you want, I think it should not be too difficult to build pagination on top of the existing `blob.Bucket` API using `ListOptions.Prefix` -- keep the last key from "page 1" as your pagination token, and then request "page 2" using `ListOptions.Prefix` set to that + `_`.

(Note that the above is pretty similar to what you have to do for at least some of provider APIs, summarized here: https://github.com/google/go-cloud/issues/241#issuecomment-426842325).

**Comment by segevfiner** [comment]
Doing pagination based on `Prefix` won't work if I'm using `Delimiter` as far as I can tell.

**Comment by segevfiner** [comment]
Doing pagination based on `Prefix` won't work if I'm using `Delimiter` as far as I can tell.

Also, we are dealing with very big buckets at times, so using a secondary index is a large problem in and of itself.

**Comment by vangent** [comment]
> Doing pagination based on Prefix won't work if I'm using Delimiter as far as I can tell.

Why not? Can you give an example?

**Comment by segevfiner** [comment]
I'm not sure if it's supported in all providers to list a prefix inside some "directory" when using `Delimiter`. e.g. "a/b/some-prefix-inside-directory" where "some-prefix-inside-directory" isn't a "directory" itself. (Directories are virtual of course, so it might actually work)

But thinking about it more, can pagination with a prefix even work at all? The prefix is a *prefix match* not a *lexicographic lower than* like in a classic DB index, so let's say you have:

* a
* b
* c
* d

And you stopped at "c", and later specify prefix "c". It will only give you "c", not the consecutive "d".

(Adding an underscore, or some other character like a null byte, is a trick for doing that in a classic DB index without looking at the next object after the page to figure out the key for the next page when doing keyset pagination)

**Comment by vangent** [comment]
> can pagination with a prefix even work at all? 
You are of course right, sorry for the confusion.

I remember that we initially thought of exposing a paged API, but ended up deciding not to because of subtle issues. IIRC One of them was differences in consistency, and another was that real pagination is hard on top of the List APIs provided. They generally have a "max" parameter to cap the # of returned items, but it doesn't have to return that many. It's OK for iteration (since you can just call again to get more), but not sufficient for what you're trying to do (pagination in a UI). Here's a snippet from the PR (https://github.com/google/go-cloud/pull/510):

```
at least for GCP APIs, the PageSize is far from sufficient for UI pagination. An API call can return any number of items <= pagesize, including 0. It is free to return a hundred zeroes (i.e. empty message except for nextPageToken), then one item, then another zero, etc.

In the GCP client libraries, we had a hard requirement from above to support exactly-N pagination. We did it with https://godoc.org/google.golang.org/api/iterator#Pager. I don't recommend we go there.
```

**Comment by segevfiner** [comment]
You got me curious on what may cause it to return less results. The GCP docs do state it may do so when using `Delimiter`, but I wonder why else it might do it.

Even so, subtle as it is, something is still needed to be able to paginate this, fetching all the results at once for a huge bucket is not reasonable unless we aim for an OOM. The UI will obviously have to adjust, knowing that it can receive fewer than the requested results and might need to send multiple calls.

AWS & GCP do support a `StartPrefix`/`startOffset` parameter, but not Azure it seems. It might be slower to paginate by it rather than by the `ContinuationToken`/`pageToken` they provide.

I assume there is no way to get at the driver from the `Bucket` and I will have to resort implementing this myself using cloud specific APIs for the time being?

**Comment by vangent** [comment]
No, there is no way to get at the driver. You *might* be able to use `ListOptions.BeforeList` callback to modify the driver call in a provider-specific way (e.g., to set a StartPrefix/startOffset).
