### ISSUE TITLE
blob: explicit multipart/resumable upload support

### ISSUE THREAD

**Issue by nbari** [google/go-cloud#291]
Could "multipart upload" be implemented for the blob storage?

**Comment by zombiezen** [comment]
Relevant docs:

- GCS: https://cloud.google.com/storage/docs/json_api/v1/how-tos/multipart-upload
- S3: https://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadAbort.html

**Comment by zombiezen** [comment]
Can you clarify what support you want, @nbari? From what I can tell, a multipart upload on GCS means that it adds metadata (which we support for the current attributes). A multipart upload on AWS seems to mean what GCS calls resumable, is that what you are after? (#222 might be related.)

**Comment by nbari** [comment]
I was searching for a way to upload a file and been available to resume the upload if for some reason the connection went down, I found that this could be done by using "multipart upload" but this implies to do a "Multipart Upload Initiation" and then a "Parts Upload".

Following the current example ([Writing the file to the bucket](https://github.com/google/go-cloud/tree/master/samples/tutorial#writing-the-file-to-the-bucket)):

```go
package main

// No new imports.

func main() {
    // ...

    w, err := b.NewWriter(ctx, file, nil)
    if err != nil {
        log.Fatalf("Failed to obtain writer: %s", err)
    }
    _, err = w.Write(data)
    if err != nil {
        log.Fatalf("Failed to write to bucket: %s", err)
    }
    if err := w.Close(); err != nil {
        log.Fatalf("Failed to close: %s", err)
    }
}
```

I found that there is a `NewWriter`,  `Write` and `Close`  but probably could be good to have a `NewMultipartWriter`, `WritePart`  `abortMultipartWriter`.

Also if I am correct when trying to do a "multipart upload" there are some [limits](https://docs.aws.amazon.com/AmazonS3/latest/dev/qfacts.html), for example:


Item | Specification
-- | --
Maximum number of parts per upload | 10,000
Part numbers | 1 to 10,000 (inclusive)
Part size | 5 MB to 5 GB, last part can be < 5 MB
Maximum number of parts returned for a list parts request | 1000
Maximum number of multipart uploads returned in a list multipart uploads request | 1000


Going furthere with the implementation the idea could be to do internaly the mulipart upload and have the method handle the  logic of spliting  the file, reading from disk the chunks/parts, upload concurrently, etc, probably  something like:

```go
MultipartUpload(file string,  cuncurent_uploads, max_parts, retries int)
```

**Comment by zombiezen** [comment]
Thanks for the writeup! We'll think about this and discuss at our next triaging meeting.

**Comment by vangent** [comment]
Some notes:

- [S3](https://docs.aws.amazon.com/AmazonS3/latest/dev/mpuoverview.html) requires the caller to maintain a fair amount of state, but allows uploading parts of the file in any order. A sample workflow is:
    - initiate the multipart upload --> record a returned upload ID
    - upload individual parts by provide an index number and the upload ID --> record a returned ETag for each
    - finalize the upload, providing the upload ID and a full list of index/ETag numbers (or, abort the upload providing the upload ID)
    - you can list the parts in an open multipart upload by providing the upload ID, but you're not supposed to use the result to finalize an upload.

- GCS has a feature called [resumable upload](https://cloud.google.com/storage/docs/json_api/v1/how-tos/resumable-upload) that's distinct from [multipart upload](https://cloud.google.com/storage/docs/json_api/v1/how-tos/multipart-upload); this feature request is about the former despite the confusing names. A sample workflow is:
    - initiate the resumable upload --> record a returned session URI
    - upload data, either in one request or in parts, via PUTs to the session URI. When using parts, the `Content-Range` header is used to describe the parts (e.g., 513-1024/5000 is bytes 513-1024 in a blob of size 5000).
    - there's no "finalize", once the server has all the bytes you're done.
    - you can resume an upload by doing an empty PUT the session URI, it will return the Content-Range that the server has (e.g., "0-1024/5000" means it has bytes 0-1024, you still need to uploaded 1025-5000).
    - It's not clear what happens if you upload a chunk out of order (e.g., you upload 0-511, and 1024-1535, but skip 512-1023). My guess is that the returned Content-Range will just say 0-511, but once you upload 512-1023, it will automagically update to 0-1535.

It looks like the GCS API wrapper we are using does chunking internally, and `blob` exposes the chunks size via the `WriterOptions.BufferSize` option. I can't tell if the GCS API internally does retries, but my guess is that it does. I doubt it uploads chunks concurrently though.

I think we have two options here:
1. Leave this as an implementation detail of the provider implementation, as it is now. So, implementations may choose, for larger files, to upload them in chunks, and retry if individual chunks fail. The GCS implementation does this now, the S3 one does not, but I think it could be changed to do so.
2. Expose it fully via the blob API.

The main advantage of (2) is that it allows the end user to persist metadata about the upload in order to be able to resume more flexibly. (1) only allows us to save the needed data in memory.

**Comment by vangent** [comment]
Removing milestone, let's discuss at our next Sprint planning meeting.

**Comment by PanchalShubham** [comment]
Is there any thought on multipart/resumable upload for `azure`? I wish to upload a large data in chunks to a specific path using `go-cloud` but it doesn't seem to provide a support for the same.  
Specific to `azure` this can be done by uploading blocks via [PUT Block](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block) request using blockId and and then committing the blocks using sequence of blockIds via [PUT Block List](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block-list) request. More specifically `blockBlobURL.StageBlock( )` and `blockBlobURL.CommitBlockList( )` would be helpful here. However I am not willing to interact directly with `azure` and will prefer to use `go-cloud` here. Any ideas on this?
