### ISSUE TITLE
server/driver: add support for Go HTTP Serve function

### ISSUE THREAD

**Issue by rootblack45** [google/go-cloud#2953]
### Is your feature request related to a problem? Please describe.

Current driver interface doesn't support HTTP Serve function that is really normal for creating a new HTTP Server without using the ListenAndServe function. This problem cause when we are trying to close one of the listeners when we serve multiple HTTP Server or want to change some default value of the keep-alive period.

### Describe the solution you'd like

Implement HTTP Serve and ServeTLS into the driver interface

**Comment by vangent** [comment]
Sorry, I'm not very clear on what you are trying to do, but I **think** whatever it is should be possible without any changes to Go CDK.

* You should not have to use the driver interface directly at all if you are using an `http.Server`. Use the `server.Server` concrete type (https://pkg.go.dev/gocloud.dev@v0.21.0/server#Server).
* The default driver provided by the package just wraps an `http.Server`: https://github.com/google/go-cloud/blob/master/server/server.go#L159. If you want to override `http.Server` settings you can create your own `http.Server` and pass it to `NewDefaultDriver`, and still keep access to the `http.Server` to call its functions whenever you want (e.g., https://golang.org/pkg/net/http/#Server.SetKeepAlivesEnabled).
* If you want to do custom things (like call `Server.Serve` with your own `Listener` instead of `ListenAndServe`), you can create your own struct that wraps `http.Server` (similar to `DefaultDriver`) and implements the needed functions from the `Driver` interface. For example, you could implement `ListenAndServe` by calling `Serve` instead.

Hope that helps.
