### ISSUE TITLE
pubsub: azuresb

### ISSUE THREAD

**Issue by Segflow** [google/go-cloud#2980]
### Describe the bug

<img width="720" alt="Screen Shot 2021-03-29 at 1 46 57 PM" src="https://user-images.githubusercontent.com/2049730/112838746-51b0cc00-9095-11eb-9b4a-9aa753050d6d.png">

I noticed that messages stopped being Received. Our service is supposed to call `.Receive()` in a loop, this was working fine -- Until recently it broke, it receives 1 message and blocks forever, while we are sure there are sill messages in the subscription. 

Using `git bisect` we found out that the bug was introduced when one indirect dependency version got bumped.

good
```
github.com/Azure/azure-service-bus-go v0.10.8 // indirect
```

bad
```
github.com/Azure/azure-service-bus-go v0.10.11 // indirect
```

We also tested with `v0.10.10` and it worked as expected.

Would be great if you can help us investigate this further. 

The service bus release that broke our services: https://github.com/Azure/azure-service-bus-go/releases/tag/v0.10.11

### Version

0.22

**Comment by vangent** [comment]
Sorry, we can't help you debug problems with the Azure library.

I did see this bug in their queue, perhaps related?
https://github.com/Azure/azure-service-bus-go/issues/216

**Comment by serbrech** [comment]
Hi,
My guess to this : 
 
We made major bugfixes to go-amqp which was not respecting flow control.
**The libraries now do respect flow control semantics**, which means that if you do not take a message disposition, the message is still considered being processed. This means that the sender will not push the next message to you, because your prefetch value says 1. and it means you want only 1 message at a time.

if you do not abandon a message, the message is locked until the lock expiration is reached, at which point the message will be re-delivered.
