### ISSUE TITLE
pubsub/pubsub: Add MessageId and PublishTime fields in Message type

### ISSUE THREAD

**Issue by anjanarvarma** [google/go-cloud#2994]
**Problem:**

Following up on this [issue](https://github.com/google/go-cloud/pull/2992), in order to access MessageId and PublishTime go-cloud pubsub Message type needs to be converted into driver-specific types using As(). Unit testing As() has its downsides and it's not possible using mempubsub pkg.

**Suggestion:** 

It would be great to expose MessageId and PublishTime in the go-cloud Message structure so that we do not need to convert this type to driver-specific types (using As())

**Comment by vangent** [comment]
Out of curiosity, what do you want to do with those fields?
IIRC, they are provider-specific. Certainly "MessageID" would at best be an opaque string. I'm not sure every provider gives a "PublishTime".

**Comment by anjanarvarma** [comment]
These fields are required to be captured in our logs for audit purposes, especially MessageId. 
It would be great to have it in the pubsub Message structure.

May I know the reason why you think MessageID is better not to be exposed?

**Comment by vangent** [comment]
What exactly do you mean by "MessageId"? I suspect you are referring to this:
https://pkg.go.dev/google.golang.org/genproto/googleapis/pubsub/v1#PubsubMessage.GetMessageId

but that is a struct (protocol buffer) that is used by GCP PubSub. That is only one provider supported by Go CDK. There may be similar/related concepts for other providers, like Kafka, AWS SNS/SQS, Azure PubSub, etc., but there is no guarantee (e.g., `mempubsub` has no such concept, although we could easily add an artificial one). I have not checked. If there is some common notion of an ID for messages, they will definitely not look the same (e.g., some maybe be strings, some may be integers, etc.). The only reasonable thing one could do with a `MessageId` if Go CDK provided it is print it out or log it, since none of the APIs use it, so I'm just not sure it's worth adding.

I will poke around to see how common it is, I get that it could be useful for debugging/logging purposes.

In the meantime, for auditing purposes, you can easily use `As`, and if the `As` call fails then you know you are using `mempubsub` and are in testing mode or whatever, so you can skip the auditing or make something up.

Another alternative would be to store some unique identifier in the message `Metadata` when you send it; then that unique ID would always be available regardless of provider.



Similarly, providers may or may not expose something corresponding to "Publish Time".

**Comment by anjanarvarma** [comment]
Yes, that's the MessageId that I was mentioning. I agree that MessageId is not used in any of the APIs, but definitely, as you agree as well, it would be a crucial(and helpful) field for logging and debugging purposes. I can work out something on PublishTime on our end which is fine.

What I have is an extractor library that captures the Message attributes (or fields) and passes the extracted data on to the logging services(like auditlog), and the main reason for checking around mempubsub (for a working AsFunc) was to unit test this extractor library with maximum test coverage. We only use GCP pubsub. Since specific driver type cannot be included in mempubsub pkg, I was just wondering why we do not have the fields MessageId and PublishTime in the go-cloud Message structure so that we do not have to use As() itself. Hence, raised the feature request.

I would like to know if it's possible to expose this MessageId as an optional field? Like only to populate it when a value(like MessageId) is present from the provider end. I get the fact that GCP PubSub is only one of the providers and other providers may have different ways(and types) of uniquely identifying a message. I am trying to understand if it's feasible here.

Also, yes, we are using As() for time being to extract those fields (MessageId and PublishTime).

**Comment by vangent** [comment]
The whole point of Go CDK is that it "provides commonly used, vendor-neutral generic APIs that you can deploy across cloud providers". As such, the Go CDK APIs only include fields and methods that are supported broadly across all providers. We use `As` to give access to provider-specific fields and methods when necessary (https://gocloud.dev/concepts/as/). We really prefer not to have fields that are only sometimes filled in as it breaks that abstraction. For example, in your case sometimes `MessageId` would have a value and sometimes not, you'd probably end up having to write a conditional there anyway; that's much more explicit when asking you to do the conditional using `As`.

I will investigate whether all providers support these concepts, but it will take some time. Until then (and depending on the result, maybe forever), you should continue to use `As`. You can detect when you're using a provder that doesn't support the specific types you are using `As` for and handle that case explicitly (i.e., by making up values for `MessageId` and `PublishTime` for the tests).

**Comment by vangent** [comment]
I sent a PR adding `Message.LoggableID`.

I don't think `PublishTime` makes sense though, fewer providers support it and it's not really clear what it means anyway for distributed systems. If you want something like this you can always continue to use `As` or add a `Metadata` key/value pair with a custom value.
