### ISSUE TITLE
pubsub/gcppubsub: Return publish error in AfterSend 

### ISSUE THREAD

**Issue by anjanarvarma** [google/go-cloud#3009]
As per the current behavior of gcppubsub, upon error on sending/publishing message AfterSend hook is not invoked.

We would like to have access to the publish error in the aftersend callback, and for aftersend to be invoked in both success and error cases. This is required for our logging and audit purposes

### Is your feature request related to a problem? Please describe.

Refer [here](https://github.com/google/go-cloud/issues/2994) for the usecase explanation
Refer [here](https://github.com/google/go-cloud/issues/2986) for the AfterSend hook request

### Describe the solution you'd like

Invoke AfterSend irrespective of Send success/failure

For success on Send, work as it is.
For error on Send, pass the publish error into the AfterSend callback.

**Comment by vangent** [comment]
If there's an error, it should be returned from `topic.Send` and you can handle it synchronously. `topic.ErrorAs` provides access to provider-specific types for the errors if you need them.

**Comment by vangent** [comment]
I don't understand. You don't need a callback; it is synchronous. Somewhere you have code like:

`
m := &pubsub.Message{...}
err := topic.Send(ctx, m)
...
`

Put your auditing code there. It has the message details in `m` and the errors status in `err`. You don't have the driver message, you have the `pubsub.Message`.

**Comment by anjanarvarma** [comment]
There are different microservices doing a send operation. We cannot have the entire auditing code in all these services, which is why we are extracting that piece of code out to another library which of course gets the pubsub Message(and could be converted to driver message as well if we need driver-specific details).  And we do set BeforeSend() and AfterSend() for capturing and logging the message details before and after sending. But in the event where there is an error in send, that error is not available in AfterSend(), and it is mandatory that we log it.

**Comment by vangent** [comment]
I am still not understanding. You need to provide the `BeforeSend`/`AfterSend` hooks in the same code path that's doing the `Send`, so I am not sure how you can avoid having the "entire auditing code" in all of the services that send messages. Perhaps you could include a code snippet showing how you are doing the `Send` and what your `BeforeSend`/`AfterSend` hooks look like.

**Comment by anjanarvarma** [comment]
Below is the sample code snippet: 

Call to extractor library from the services. This library eventually passes on the captured data to audit logging services :

```
extractor.Log(ctx, pubsub.Message)// call the extractor service to extract the data and provide the data to the logging services
err := topic.Send() // send error is captured here in the service
///Rest of the service code//
```

Within the extractor library we have the Log func:

```
func Log(msg pubsub.Message){
// set the beforeSend callback to log the data just before sending
beforeSendCallback := func(asFunc func(i interface{}) bool) error {
        if ok := asFunc(&nativeMsg); ok {
           // capture details before send for logging
        }
        return nil
    }
    msg.BeforeSend = beforeSendCallback  // set the beforeSend call back

// set the afterSend callback to log the data just after sending. We don't get the send error here
    afterSendCallback := func(asFunc func(i interface{}) bool) error {
        var messageID string
        if ok := asFunc(&messageID); ok {
           // capture details after send for logging
            return nil
        }
        return nil
    }
    msg.AfterSend = afterSendCallback // set the afterSend call back
}
```

As you can see from above, the publish error is thrown at the service side, and it's not available in afterSend because as per the internal gcppubsub code AfterSend() is not invoked if there is a publish error. 

But instead, if we have the publish error passed to AfterSend callback, we could get the error in the extractor library and log it for internal audit use. Or, is there any other way you think we could capture the publish errors here in the library?

**Comment by vangent** [comment]
All of this is happening in the same process so you should be able to do this in your code.

For example, you could do something like this:

```
errCallback := extractor.Log(ctx, m)
err := topic.Send(m)
if err != nil {
  errCallback(m, err)
}
```

and then in the extractor library:

```
func Log(msg pubsub.Message) (func(error, pubsub.Message)) {
  // Your existing code.
  return func(err error, m pubsub.Message) {
    // Log/audit the error
   }
}
```

or, alternatively, you could add a `LogError(msg pubsub.Message, err error)` function to the extractor library and call it explicitly when there's an error.

**Comment by emmaCullen** [comment]
Hi @vangent , I am just catching up on this thread. Yes it is possible to handle this error in a multitude of ways on our side. 

However, we are wondering what is the reason for not exposing the return status in the afterSend function? 

If you are providing a callback that is intended to be invoked after a send, then imo it would make sense to also expose the result of the send. Otherwise, would you please be able to expose the message details in the return value from topic.Send()? Forcing us to split our post send handling does not seem like the correct approach here, unless there is some other reason that I am missing.

**Comment by vangent** [comment]
> what is the reason for not exposing the return status in the afterSend function

The intent of these callbacks is to expose provider-specific data that's otherwise not available. The return status is already available in the error returned from `Send`.

> would you please be able to expose the message details in the return value from topic.Send

I am not sure what you mean by this. The message details are in the message that you passed to topic.Send, on the same line that you're getting the error message back. They should be easily available to the code there.

You do not need to split your post-send handling, it should be pretty straightforward to set up some local variables, have your `AfterSend` callback update them, and then use those variables + the error return to do the post-send handling.

```
var foo string
var bar int
msg.AfterSend = func(asFunc func(interface{}) bool) error {
  // Use asFunc to get provider-specific data and set foo, bar based on it.
  return nil
}
err := topic.Send(ctx, msg)
AuditSentMessage(err, foo, bar)
```

**Comment by emmaCullen** [comment]
> > what is the reason for not exposing the return status in the afterSend function
> 
> The intent of these callbacks is to expose provider-specific data that's otherwise not available. The return status is already available in the error returned from `Send`.
> 
> > would you please be able to expose the message details in the return value from topic.Send
> 
> I am not sure what you mean by this. The message details are in the message that you passed to topic.Send, on the same line that you're getting the error message back. They should be easily available to the code there.

The message details I am referring to are the "provider-specific data that's otherwise not available". This design is forcing the user to have to implement handling in two places, I am wondering what is the reason for that when you could easily include the return code in AfterSend. 
> 
> You do not need to split your post-send handling, it should be pretty straightforward to set up some local variables, have your `AfterSend` callback update them, and then use those variables + the error return to do the post-send handling.
> 
> ```
> var foo string
> var bar int
> msg.AfterSend = func(asFunc func(interface{}) bool) error {
>   // Use asFunc to get provider-specific data and set foo, bar based on it.
>   return nil
> }
> err := topic.Send(ctx, msg)
> AuditSentMessage(err, foo, bar)
> ```

This snippet seems over engineered and fragile to future bugs, why would we do it this way when you could just include the return code in the AfterSend parameter?

Either way, there are still two points in run-time that the handling is occurring,  even if the first part of the handling is merely saving the message data in the local variable. This is an issue for our audit when we have to provide legally robust "point in time" proof of a monetary transaction. 

Of course we will make do with whatever we have to, we do appreciate your taking the time to code up these workarounds, and if it becomes an ongoing issue for our needs we can always consider moving to another library - however I have still not heard a reason to not expose the error response in the AfterSend.

**Comment by vangent** [comment]
It is not good API design to return the same data in multiple different ways, and it increases the requirements on all of the driver implementations to get it right.

There are inherently two conditions here, error and success, if you want provider-specific data for each then it is inevitable that you will have at least two lines of code to do that.
