### ISSUE TITLE
What is the state of this project?

### ISSUE THREAD

**Issue by asim** [google/go-cloud#3021]
I'm curious to know what the state of this project is at Google? Is there's a product manager for it? Is it supported as a full time initiative? Are there multiple devs working on it? Just curious for anyone committing to using it.

**Comment by eliben** [comment]
Hi @asim!

While I can't divulge details on the Google staffing for this project, it *is* being maintained. Issues are fixed; new releases are made, and according to pkg.go.dev it has quite a few importers.

It's important to point out, however, that this is a project with a limited scope - and that's by design. A project of this kind is not expected to change a lot; for example, to offer new functionality in the `blob` package there would need to be similar changes in all major `blob` providers. The idea here is to provide portable APIs over common subsets of functionality for very established services, so the change rate is expected to be slow. This is also why new features / services are hard to accept.

If you have any specific use cases for `go-cloud` in which you'd be interested, please open a separate issue.

**Comment by maguro** [comment]
I submitted a PR to provide signatures.  Would this better be placed in a separate, dependent, project?
