### ISSUE TITLE
blob/all: support for URLs with keys

### ISSUE THREAD

**Issue by 56KBs** [google/go-cloud#3103]
### Is your feature request related to a problem? Please describe.

When using the blob package it frustrates me that bucket URLs are handled separately from the object key .

For example, I have a CLI application that reads the location of a TLS certificate and a private key - I'd really like to be able to allow end users of the application to define a single URL to the file and have as little code as possible for me to load that. Currently the most simple solution is to require two sections of the CLI option, one containing the bucket URL, the other containing the key name within that bucket.

Another example I have is that I have a service receiving RPC calls, embedded within these calls is the location of a file that needs to be processed, I'd love to be able to use a single URL to locate this file, as this feels more intuitive than containing two fields in the RPC to signify this data.

Some examples of URLs containing the key:
- `s3://example-bucket/path/to/key.txt`
- `s3://another-bucket/key.txt?region=us-west-1`
- `file:///home/root/file.txt`

### Describe the solution you'd like

As a user I would like to be able to use blob URLs with keys so that I can simplify my code base.

The most helpful thing I can think is for a helper method within `blob` that splits the bucket name from the key. For example: `blob.SplitBucketFromKey(u *url.URL) (bucket *url.URL, key string, err error)`

This would allow me to accept a URL that contains the key and handle opening of the bucket & reading the file.

### Describe alternatives you've considered

As a large number of my use cases for this are low frequency read/writes I also considered the addition of `blob.NewReader(ctx context.Context, u *url.URL, opts *ReaderOptions) (*Reader, error)` that accepts a URL containing the key. This method would open the bucket, calling `NewReader` on this bucket. I am now sure how the closing of buckets would be affected in this scenario, as the bucket could be closed prior to the reader being used.

I had also considered the same for `blob.NewWriter(xxx)`

### Additional context

Consideration may need to be made for the `prefix` option on blobs, because it may make the URLs somewhat un-intuitive, for example `s3://example-bucket/key.txt?prefix=/path/to/` - Additionally implementation may be complex due to double slashes, etc.

I have a personal repository that already performs this kind of splitting on URLs for a sub-set of the blob drivers (s3blob, fileblob).

**Comment by vangent** [comment]
Another option here is to treat it like a `PrefixedBucket`, except that instead of adding a prefix to every key, it would use a preset static key (and ignore any passed-in key). This would work best if the "filename" is specified as a URL parameter, not as part of the URL path itself, as different drivers using different parts of the URL path in different ways.

* It would work for any driver as this would implemented at the `blob` level.
* You would call `OpenBucket` with a URL as normal, and if the URL had a "only_key" URL parameter (or whatever, naming TBD), you would get a `*blob.Bucket` back that you could call various methods read/write methods/etc. on with an empty-string "key" parameter, and the key would get filled in with whatever you put as `only_key`. `List` wouldn't work.

WDYT?

**Comment by vangent** [comment]
See https://github.com/google/go-cloud/pull/3105 for example of the above, feedback welcome.

**Comment by vangent** [comment]
I went ahead and checked in my change because it was simple and I think it could be useful for a use case like yours. You just open the bucket with the URL and read from it, passing "" as the `key`. I agree that the URL format is a bit wonky (e.g., `file://my/directory/path?key=my_filename.txt`, but I think that's necessary to make the semantics clear.

**Comment by 56KBs** [comment]
Whilst disappointing - I understand, I'll continue to handle my own mapping from a full URL into a bucket & key. On a sidenote - Supporting prefix doesn't fully make sense in the use-case you want a URL with a bucket & the key, because that implies you want to work on a single file, not a file within a directory, as such I've disabled prefix support in my mapping code.

The `key` parameter does help slightly simplify my code however, so thanks :)
