### ISSUE TITLE
blob/s3: Support Server Side encryption settings in bucket url

### ISSUE THREAD

**Issue by tristan-newmann** [google/go-cloud#3337]
### Is your feature request related to a problem? Please describe.

I am attempting to use go-cloud  with an S3 bucket that has a bucket policy that enforces Server Side Encryption and a specific KMS key for uploads. 

I am unable to use go-cloud to do this in the context of third party tool, since it does not currently implement support for S3 specific settings using `As` and `BeforeWrite`. See also https://github.com/pulumi/pulumi/pull/14476

### Describe the solution you'd like

Allow configuring of server side encryption settings that are added to the S3 headers via new query parameters in the bucket URL. This would be similar to #3008

### Describe alternatives you've considered
In https://github.com/pulumi/pulumi/pull/14476, I implemented support using `As` and `Before`,  but the maintainer preference if this is supported directly in go-cloud via url params

### Additional context
See also https://github.com/google/go-cloud/issues/2802. I am mainly checking to see if there is appetite to support this sort of feature now (I am happy to submit the contribution) since it seems like a couple of third party tools have not added support for this, and it would be handy if it was handled automatically by go-cloud

**Comment by vangent** [comment]
It seems OK to me. I don't think these parameters are supported in the aws.Config (correct me if I'm wrong through), so rather than modifying `V2ConfigFromURLParams` (https://github.com/google/go-cloud/blob/master/aws/aws.go#L181), you'll need to add them to `Options` (https://github.com/google/go-cloud/blob/master/blob/s3blob/s3blob.go#L173), override them in `OpenBucketURL` based on the URL parameters (near https://github.com/google/go-cloud/blob/master/blob/s3blob/s3blob.go#L164), and use them (https://github.com/google/go-cloud/blob/master/blob/s3blob/s3blob.go#L959, https://github.com/google/go-cloud/blob/master/blob/s3blob/s3blob.go#L1032, possibly `Copy` https://github.com/google/go-cloud/blob/master/blob/s3blob/s3blob.go#L1105).

Local testing plus URL tests (https://github.com/google/go-cloud/blob/master/blob/s3blob/s3blob_test.go#L459) should be fine.

**Comment by tristan-newmann** [comment]
Thanks for the quick response! I followed the guidance here and got an initial draft of this working locally passing the values through `Options` (as you noted, these aren't available in `aws.Config` since they are only associated with specific requests). 

I should have an MR up sometime early next week for review
