### ISSUE TITLE
all: cloud load balancing

### ISSUE THREAD

**Issue by rc979** [google/go-cloud#554]
Are there plans or interest in developing abstractions for cloud load balancers?

**Comment by vangent** [comment]
@rc979 Can you point to any Cloud load balancing API(s) that could be abstracted?
FYI, in general we are less interested in the provisioning APIs, since there are a number of tools (like Terraform) addressing that need. We're focused on Cloud services. For example, `blob` is an abstraction over [S3](https://godoc.org/github.com/aws/aws-sdk-go/service/s3) and other equivalents.

**Comment by rc979** [comment]
I was thinking of ELB and GCP's external and internal load balancers for example and have a set of set of CRUD API calls for the VIP and its members and maybe a couple of other mechanisms for migrating and draining flows between backends. It's true that Terraform does some of the work but it seems to me there's still a fair amount of work that needs to happen and the integration (and testability) with native Go code doesn't seem trivial from what I've seen. What do you think?

**Comment by vangent** [comment]
Thanks for the suggestion! This feels more like provisioning and less like something you'd do when writing an application, which is our main focus right now, but I'll leave this feature request open and we'll see if we get more requests for it.
