### ISSUE TITLE
pubsub/driver: add As functions for Topic, Subscription, and Message

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#657]
This change was suggested by @vangent on pull #643:

> See blob.Driver for examples.
> 
> Message is used for both reading and writing, which makes it interesting for As. An As function As(i interface{}) bool makes sense for reading, but for writing you want to give access to the underlying type of whatever message is going to be sent to the server. In blob, we do this via WriterOptions.BeforeWrite. So you could:
> 
> Add a BeforeWrite-like function to Message, that's only used when writing
> Split Message into separate types for reading (with As) and writing (with BeforeWrite)
> Add an Options struct with BeforeWrite to SendBatch.

**Comment by ijt** [comment]
... and I suppose it would make sense to have the same method on `Subscription` to handle the conversion for received messages.

**Comment by vangent** [comment]
`Message.As` is better than `Subscription.MessageAs` for received messages.


For sent messages, I don't think your suggestion works for the actual lifecycle of the message objects. It definitely did not for `blob`. The lifecycle looks something like:

1. User creates a `pubsub.Message` and sets some fields.
2. User calls concrete type's `Send` and passes the message <blocks here>.
3. Concrete type converts `pubsub.Message` to `driver.Message` and adds the message to a batch.
4. ... at some later point, the batcher decides to send the batch and calls `driver.SendBatch`.
5. The driver converts the `driver.Message` to the provider-specific type and sends it.
6. User's `Send` returns.

Note that the provider-specific type is not created until 5). It definitely does not exist before 2) when the user could call something (they are blocked after 2) ). It is also desirable that the provider-specific type the user gets access to via `As` is filled in as much as possible (e.g., the `Body` field, etc.) so that they can override things if they want to. That doesn't happen until 5).

The `blob` solution is for the user to provide a callback function (in `Options`) that accepts the `As` function the user can use:

```
BeforeWrite func(asFunc func(interface{}) bool) error
```

**Comment by jba** [comment]
Looks like we'll need `TopicOptions.BeforeSend`.

I'm not really sure on why we need `asFunc`. Couldn't BeforeSend take an `interface{}` which holds the actual message type? The user of BeforeSend must already know that type to call `asFunc`.

**Comment by jba** [comment]
BTW, I think the same criticism applies to blob's BeforeWrite.

**Comment by ijt** [comment]
@vangent, there is no driver interface component of `Message`, so there's no way to make a useful `Message.As`. That's why I suggested putting `MessageAs` methods on `Topic` and `Subscription`: because they both of have driver interface components that can do different things depending on the provider.

The information from the `driver.Message` that gets put into the provider-specific message can be extracted from it at any time and used to create an equivalent provider-specific message, so I see no reason to make the logic more complicated just so we can return a copy of the provider-specific message that we construct right before sending. But maybe I'm missing something. I suggest we chat about it.

**Comment by jba** [comment]
I think the idea is to give back the _actual_ provider-specific message, not a copy, so that the caller can make changes.

**Comment by ijt** [comment]
I see. In that case we'll have to replace `Topic.MessageAs`, but I think `Subscription.MessageAs` still makes sense.

**Comment by vangent** [comment]
> there is no driver interface component of Message, 
> so there's no obvious way to make a useful Message.As

Please take a look at `blob.Attributes` for a previous example of this. The concrete type has an `As` func, which ends up calling an `AsFunc` that the driver needs to set (if it is left `nil`, then `As` returns false).

**Comment by ijt** [comment]
@vangent, isn't that pretty close to what I said just above your comment?

Do you disagree that `Subscription.MessageAs` is clearer for received messages?

**Comment by vangent** [comment]
> isn't that pretty close to what I said just above your comment

Yes, it is close. There's a public `As` function defined for `pubsub.Message` that uses `Message.as`, and `driver.Message.as` needs to be public (`As`) so that the concrete type can access it.

> Do you disagree that Subscription.MessageAs is clearer for received messages

I think it's clearer and more standard to have the function on the struct that it's referring to -- so, `Message.As`.

Notice that we already have `Message.Ack` which only applies for received messages, so this isn't the first time that `Message`'s dual-purpose nature is coming up. We can either document these clearly, or split `Message` into two types, one for receiving and one for sending. I don't remember if we discussed that before.

**Comment by jba** [comment]
Let me try to summarize:
```
pubsub.Topic.Options.BeforeSend func(asFunc...) error (?)

driver.Message.AsFunc func(interface{}) bool

pubsub.Message.asFunc func(interface{}) bool // populated in concrete impl from driver.Message.AsFunc

pubsub.Subscription.MessageAs(*pubsub.Message, interface{}) bool // calls pubsub.Message.asFunc
```
This differs from blob in that we don't have a `Message.As` method. It's clearer to have that on `Subscription`, because it only makes sense for received messages.

**Comment by vangent** [comment]
>  It's clearer to have that on Subscription, because it only makes sense for received messages.

Hmm, then why do we have `Message.Ack` instead of `Subscription.MessageAck`?

**Comment by jba** [comment]
That's a fair question.

I think it's extremely unlikely that someone would call `Ack` on a message they intended to publish. Someone who did that would have a fundamental misunderstanding of the pubsub model.

On the other hand, it would be relatively easy to fall into the trap of calling `As` on a to-be-published message with the intent of influencing the outgoing message. We fell into that trap ourselves until you spelled it out above.

If the symmetry with `blob.Attributes` is important to you, then we could have `Message.As` panic in that case. 

I guess I don't have a strong preference between these two.

(By the way, I just realized that if we use `Subscription.MessageAs`, then we don't need the two `asFunc` fields, so my summary is wrong.)

**Comment by vangent** [comment]
Given that we now have two functions that are only for received messages, and I suspect we will next need to add something only for sent message (`BeforeSend` or whatever, the callback for `As` before sending), WDYT about having 2 separate `Message` types?

**Comment by vangent** [comment]
(this would also make it easier to have, say, a "Received Time" field on the received message, etc.).

**Comment by jba** [comment]
That would make it painful to write forwarders, proxies, multiplexers and the like. (That is, something that receives messages from a subscription and then publishes the same messages.) I don't know if that's common.

Cloud Pub/Sub has [two message protos](https://github.com/googleapis/googleapis/blob/master/google/pubsub/v1/pubsub.proto#L609), but the receive one contains the publish one, so forwarding is easy.

**Comment by vangent** [comment]
Good point about forwarding.

> the receive one contains the publish one

We could do that in the driver... On the concrete type, we could do that as well, or have two separate types, where the "send" one can be constructed given a "received" one (e.g., `func (r *ReceivedMessage) Forward() *Message {}`).

I feel like we're getting signals here that we shouldn't be using the same type for both though.

**Comment by ijt** [comment]
@vangent, I agree that splitting `Message` into something like `OutMessage` and `InMessage` is starting to make sense. Open to bikeshedding on the names.

@jba, an alternative to containment would be to have `OutMessage` and `InMessage` without containment and with a method like `OutMessage.ToInMessage()`. WDYT?

**Comment by jba** [comment]
Since there are no methods on the message type being sent, I think containment is simpler. But either way is fine.

**Comment by jba** [comment]
This issue got derailed into the discussion of splitting message types. We decided in #903 not to do that. So that leaves us with the question of where to put the `As` function for messages: on Message, or on Subscription.

I don't have a strong preference, except that we must fail dramatically if As is called on a message that was not obtained via Receive. (That is, panic rather than return false.) The reason, as I said upthread, is that someone doing that would deeply misunderstand how our package works.

**Comment by vsaroopchand** [comment]
Just to add my 2-cents to the conversation, so far, it seems the conversation is focused on adding As/AsFunc before the message is sent. From an Azure perspective, this is not really important because the two primary properties (Body & Metadata) can be set on the driver.Message.
In the Azure ServiceBus SDK, the Message object does many important functions such as renewing a lock; completing or rejecting a disposition; system properties; deadlettering, etc. As it stands with the current driver API, none of these important operations are accessible! The go-cloud client should be able to access the underlining provider message using As(interface{}) especially for Azure so go-cloud clients are not sacrificing capabilities with this abstraction.

**Comment by jba** [comment]
> Message object does many important functions such as renewing a lock; completing or rejecting a disposition; system properties; deadlettering, etc.

That's all for a message that you've received, right? You can't do anything with a Message before you send it.

Some of us worry that a `Message.As` method might be called by somebody on a Message that they're going to send, which wouldn't make sense. That's why the alternative proposal is `Subscription.MessageAs`, so it's clearer that

**Comment by vsaroopchand** [comment]
@jba Correct, the missing functions listed are for received messages. We need to support these for completeness. Your proposed solution (return false if called early) will work.

**Comment by jba** [comment]
@ijt @vangent Are you OK with `Message.As` that always returns false if it wasn't received?

**Comment by vangent** [comment]
I don't feel strongly about panic vs false in that scenario.

**Comment by ijt** [comment]
It's probably not going to happen that often, but it seems like `panic` is the right choice in that situation.

**Comment by jba** [comment]
@ijt, do you mind if I take this from you? Or are you working on it?

**Comment by ijt** [comment]
Sure, I don't mind. I'm not working on it right now.
