### ISSUE TITLE
pubsub: dynamically adjust number of messages fetched by Receive

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#691]
It could be that multiple machines are needed to handle the messages coming in on some subscription. It would be best if the concrete API would dynamically adjust the max number of messages being pulled in ReceiveBatch, which would then have to take that as a parameter.

**Comment by vangent** [comment]
We may also want to proactively call `ReceiveBatch` before there are 0 messages left.

We may also want to call `ReceiveBatch` concurrently (today, the driver interface says it must be callable concurrently, but we never do).

**Comment by jba** [comment]
Here is one way to pick the maxMessages value to pass to `ReceiveBatch`.

We want to keep a few messages in memory at all times, so callers of `Receive` can get a message right away. But we don't want to keep too many around: if it takes too long to start processing the messages, they might expire (their ack deadline might be exceeded); and there might be other subscribers who could be handling those waiting messages.

So we want to aim for the in-memory queue of messages to be a certain size. What is a good size? If you think in terms of number of messages, that is hard question. Is 10 a good size? If messages are processed in a millisecond, it's too small—those ten messages will probably be consumed before an RPC to get more will return. If it takes two minutes to process a message, then 10 is too large—the last message will be sitting around for 18 minutes, which feels like along time (and exceeds the maximum ack deadline on Google Cloud Pub/Sub).

It makes more sense to measure the size of the queue in *time*. A queue that is 2 seconds long will give the next RPC 2 seconds to refill it, will make messages wait at most 2 seconds before being processed, and will result in only 2 seconds of lost work in a crash.

To measure the queue in time, we need to know how long it takes to process one message. So we keep track of the average time it takes to do so. Since the value can change over time, we keep a running average over some interval, say one minute.

We could measure processing time as the interval between the return of `Receive` and the call of `Ack`.  But not every message will be acked. It is perfectly reasonable for a subscriber to nack (or fail to ack) a significant fraction of the messages it receives. Processing time for those unacked messages should still be included in the average.

So we should measure processing time from the return of `Receive` until the next call to `Receive`. That calculation will be confused by concurrent calls to `Receive`, but only in the short term. In the longer term, it should provide a pretty good sense of the average processing time. 

With the average processing time in hand, and a desired queue length in time, we can calculate how many messages to ask from `ReceiveBatch` when the queue is empty:
```
messagesToRequest = desiredQueueLengthInTime / processTimePerMessage
```
For example, if we want the queue to be 2 seconds long, and it takes 100ms to process a message (10 per second), then we should ask for 2 / .1 = 20 messages.

I implemented this idea in #1200. It only makes the ReceiveBatch call when the queue is empty, and never makes more than one at a time, so there is still room for improvement. But it still quadruples the benchmark speed for GCP, while reducing the number of in-memory messages when processing is slow.

**Comment by jba** [comment]
That's much simpler. But I think the main problem is that it doesn't give you a goal to aim for. Let's say tfetch = 1s and tproc = .5ms. So maxMessages = 2000. But Cloud Pub/Sub will only give you 1000. So you keep asking for 2000, keep getting 1000, and ... then what? You think you're fine—nothing's telling you that you're falling short.

If you knew you were falling short, you could do something like make two calls concurrently. That's where I think tfetch comes in: if you need 2000 messages in the next second to have an adequate buffer, and you've calculated that tfetch is less than 2000 msgs/sec (I think it's more-or-less linear, BTW, from eyeballing gcp pubsub latencies), then you make multiple calls.

**Comment by ijt** [comment]
Good point about the linear model. We can model the fetch time for `n` messages like this:
```
tfetch(n) = a + n * b
```
Once we've measure the times taken for 1 message and `n > 1` messages then we can estimate `a` and `b` as
```
b = (tfetch(n) - tfetch(1)) / (n-1)
a = tfetch(1) - b
```
We want the fetch to terminate about when the local queue runs out. If there are `nlocal` items in the local queue, then that should happen about `nlocal / tproc` from now, so we want to fetch
```
tfetch(n) = nlocal / tproc
a + n * b = nlocal / tproc
n = (nlocal / tproc - a) / b
```
Then we would have to figure out the number of concurrent fetches to run based on the provider's max batch size.
```
maxMessages = min(providerMax, n)
ng = ceil(n / maxMessages)
```
Then run `ng` concurrent calls to `ReceiveBatches(maxMessages)`.

**Comment by ijt** [comment]
I think it's too confusing to compute `tproc` the way I proposed when there are multiple goroutines receiving messages. One way to solve it that handles that situation easily is to mark each message with a timestamp `tr` when it is received. Then if it is acked later we set `tproc = now() - tr` for the subscription. We can do a weighted average of recent `tproc` values if it's too noisy this way.

**Comment by jba** [comment]
> It's not clear which starts of which `Receive()` calls go with the ends of which others.

You're right, that's a bug. Say goroutines A and B call Receive concurrently and both return about the same time. Then A takes 10ms to process the message and B takes 11ms. As soon as A is done, it calls Receive and gets another message; I record a time of 10ms. One ms later, B calls Receive and gets a message. I record a time of 1ms. The right average is 10.5 but I get 5.5.

**Comment by jba** [comment]
We could remember the time we give out each message, and when Receive is called at some time `t`, record a processing time of `t` minus the time of the oldest message we gave out. Then drop that oldest time. Then I don't think it matters what order Receive is called in.

That sounds like it takes a lot of memory, but it's the same if we record time to ack: we need to store one time per message.

However, I agree that time-to-ack is easier to think about. And someday we'll probably (almost certainly) have Nack, and then the only applications we'll be neglecting are the ones that let messages expire, and I don't think that's done too much.

**Comment by jba** [comment]
> `n = (nlocal / tproc - a) / b`

I agree we have to have some model of how long the RPC takes (even if that model is a constant), and my idea is missing that. But I think this is the wrong way to use that information.

First, it should be `nlocal * tproc`, but otherwise I think the idea makes sense. It says, we have some time before the buffer runs out, so lets fetch _as many messages as possible_ in that time. What I think is wrong about it is that there is no limit on how many messages you could get, and therefore how large your backlog of messages grows. We don't want to stall—this accomplishes that—but we also don't want to have too many messages in memory. 

So I still prefer the idea of aiming for a particular buffer size. But we have to combine it with some idea of how long an RPC takes (`tfetch`), so we know when to start refilling the buffer, and we can decide how many concurrent calls to make.

Let's assume to start that `tfetch` is a constant. Then when the buffer duration (its size measured in time) gets down around `tfetch`, we want to make an RPC. Say at `2 * tfetch`, just to make the math easier for now.

How many messages do we want to ask for in the RPC? When the RPC returns, the buffer duration will be `tfetch` (it's `2*tfetch` now and the RPC will take `tfetch` to run). We have some desired buffer duration `D` (what I called `desiredQueueLengthInTime` upthread). So we want 
```
n = (D - tfetch) / tproc
```
messages. 

Example: it takes 1s to make an RPC (`tfetch`) and 100ms to process each message (`tproc`), and we want a 5s buffer (`D`). When the buffer gets to 2s (twice the RPC time), we start an RPC. We want `(D - tfetch) / tproc = (5s - 1s) / 100ms = 40` messages.

That's where we would stop if `tfetch` is constant: there's no need for concurrency if your RPC always takes the same amount of time. I'm avoiding talking about the max number of messages that a provider allows per RPC. We may need that, but I'm hoping we don't. For one thing, I don't think GCP actually states the limit (see the [limits page](https://cloud.google.com/pubsub/quotas), which some some other interesting limits we should be aware of).

If `tfetch` were a linear function of `n`, then we'd still say we can finish the RPC in 1s. We'd calculate `n` as above, then plug it into `tfetch(n)`. If the number was greater than 1s, we'd parallelize. E.g. if `tfetch(n)` was 5s, we'd start 5 concurrent RPCs.

I don't think this is the whole story, because when we do start concurrent RPCs, they'll return at different times. So at any moment we will have a few outstanding RPCs, and that needs to factor in somehow. I'm hoping there's a simpler way to think about this that doesn't require adding more epicycles.

**Comment by ijt** [comment]
Hmm, I don't understand this. We still don't know which goroutine this new `Receive` was called from so we don't really know what timestamp to subtract from `time.Now()`.

I'm still in favor of the ack based approach and getting more accuracy when we add nacks.

**Comment by jba** [comment]
> We still don't know which goroutine this new `Receive` was called from so we don't really know what timestamp to subtract from `time.Now()`.

I doesn't matter. Say one goroutine starts at `s1` and finishes at `f1`. Another starts at `s2` and finishes at `f2`.  The average time is
```
((f1 - s1) + (f2 - s2)) / 2
```
But that is the same as
```
((f1 - s2) + (f2 - s1)) / 2
```
So it doesn't matter how you pair them up.

**Comment by ijt** [comment]
Fair point but if anyone tries to add in decay or just use the latest value
they'll get a bug if it depends on being able to rearrange that way.

**Comment by vangent** [comment]
This was done in https://github.com/google/go-cloud/pull/1200. I'll file a separate issue for additional performance improvements for pubsub.
