### ISSUE TITLE
all: windows builds keep flaking

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#696]
See for example https://github.com/google/go-cloud/pull/693/checks?check_run_id=31559768. This happened twice in a row and each time takes 15 minutes to run, so running it again isn't really a viable solution. Let's disable the Windows builds until we get the flakes under control.

**Comment by vangent** [comment]
Is there evidence that it's flakier in Windows? We've seen the in
non-windows builds too, and it has definitely passed on Windows. 2x in a
row isn't enough to convince me that disabling is warranted.

**Comment by ijt** [comment]
Slightly more evidence: the PR that turns off the windows builds is green.

**Comment by ijt** [comment]
Here's another instance where it failed on Windows but not on the others: https://github.com/google/go-cloud/pull/685/checks?check_run_id=31538714.

**Comment by vangent** [comment]
https://github.com/google/go-cloud/pull/699/checks?check_run_id=31801029
  failed for osx with the same error, but passed for linux and windows.

**Comment by zombiezen** [comment]
The root cause of this particular flake and workarounds are being discussed in #669. I would prefer not to have the conversation split among two separate issues. The current suspected source of the problem is the Go tool, not anything OS-specific. As such, I don't believe the right course of action is to disable Windows builds.
