### ISSUE TITLE
pubsub: should Subscription constructor take a context?

### ISSUE THREAD

**Issue by ijt** [google/go-cloud#815]

**Comment by ijt** [comment]
1. Take context in NewSubscription, updating all uses.
2. Replace sleep call in TestAckDoesNotBlock with a context whose cancel gets deferred.

**Comment by vangent** [comment]
The real question here is whether `NewSubscription` should take a context.

@jba 

Currently, IIUC, `sub.Close()` could block forever, because it waits for in-flight acks to be sent, and the RPCs for those acks use a context that `Subscription` created internally. "Block forever" doesn't sound great. However, having the user pass a context in to `NewSubscription` and then cancel it before `Close` doesn't work well either, because then all of the in-flight acks will fail (due to their ctx being cancelled).

One option would be to have `Close` take a ctx, and guarantee to return quickly after that ctx is cancelled. Other ideas?

**Comment by jba** [comment]
I like `Subscription.Close(ctx)`. That puts the context in the right place.

**Comment by jba** [comment]
Oh, and `NewSubscription` should not take a context.

**Comment by ijt** [comment]
I got my test to work without the sleep hack and without modifying `NewSubscription`, although unfortunately now the test times out to signal failure.

https://github.com/google/go-cloud/pull/802/commits/1ece95c25652360eefde83ad9443c24a88b76357

**Comment by ijt** [comment]
Anyway, given the current title of this issue, I think we can mark it closed.

The answer is no, `NewSubscription` should not take a context argument.
