### ISSUE TITLE
all: too many packages at the top level make godoc hard to use

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#918]
Feedback from a user was that there are too many top-level packages (e.g., see [godoc](https://godoc.org/github.com/google/go-cloud)), many of which are very small (e.g., `health`), or are just wire providers (e.g., `aws`, `gcp`), or are internal (`samples/...`, `internal/...`). It was hard to find the interesting packages like `blob`.

**Comment by eliben** [comment]
Not sure what we can/want to do about this. Maybe just mention gocloud.dev more prominently on top of the main docstring?

**Comment by zombiezen** [comment]
I'm closing this issue because two things have changed since the issue was opened:

a) gocloud.dev hosts docs with much better discovery of sub-packages
b) [doc.go](https://github.com/google/go-cloud/blob/e3028af50b502e550c82abdc8435acd90a5bdeae/doc.go#L36) now mentions the gocloud.dev site prominently.
